import type { Lesson } from './types'

/**
 * Comprehensive curriculum for 36-week homeschool year
 * Monday/Thursday: Core + Art
 * Tuesday/Friday: Core + Science + Library Mission
 * Wednesday: Co-op (no regular coursework)
 *
 * Structure:
 * - Learning Objective: Single, measurable skill
 * - Biblical Connection: How this connects to faith
 * - Materials: What teacher/child needs
 * - Mom Time: 5-10 min teaching script + steps
 * - Guided Practice: Teacher demonstrates, child observes/participates
 * - Independent Activity: Child does mostly alone (worksheet or hands-on)
 * - Answer Key: Expected responses or solutions
 * - If Struggling: Support strategy
 * - If Advanced: Challenge extension
 */

// ==================== WEEK 1: God Created Me & My World ====================

const week1Lessons: Lesson[] = [
  // Monday Pre-K: Literacy
  {
    id: 'l-w1-mon-pre-k-lit',
    title: 'I Am Special (Letter M & I)',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 1,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 8,
    essential: true,
    owner: 'shared',
    learningObjective: 'Recognize and name letters M and I; connect to self-identity',
    biblicalConnection: 'God made me and I am special to Him (Genesis 1:27)',
    materials: ['Picture cards of body parts', 'Large M and I letter cards', 'Crayons', 'Worksheet'],
    momTime: {
      duration: 8,
      script: `Today we're learning about YOU and how special you are. God made you, and that makes you special! We're learning two letters: M for Me and I for I. Let's say them together. M is for ME! I is for I! Let's look at our body parts - eyes, nose, mouth. Can you point to YOUR eyes? Now trace this big letter M with your finger. Good! The letter M looks like two mountains, and YOU are wonderful like a mountain!`,
      steps: [
        'Introduce self-identity: "God made you special"',
        'Show M and I letter cards, say sounds together',
        'Point to body parts on own body',
        'Trace large M and I letters with finger',
        'Color self-portrait together',
      ],
    },
    guidedPractice: {
      description: 'Teacher shows body part pictures, child names them and traces',
      example: 'Teacher points to eye picture. Child says "eye" and traces E in the picture',
    },
    independentActivity: {
      description: 'Complete worksheet with body part matching and letter tracing',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'I Am Special (Tracing & Matching)',
      fileUrl: '/worksheets/week-01/pre-k/Monday_Literacy_Introduce.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Letter Hunt',
      fileUrl: '/worksheets/week-01/pre-k/Challenge_Letter_Hunt.pdf',
      description: 'Find multiple M and I letters in pictures, sort by shape',
    },
    answerKey: 'Matching: eye-eye, hand-hand, ear-ear. Traced M and I shown on worksheet.',
    ifStruggling: 'Focus on just M. Trace together multiple times. Skip I for now.',
    ifAdvanced: 'Find M and I in words around house (Mom, I, It, me)',
  },

  // Monday Pre-K: Math
  {
    id: 'l-w1-mon-pre-k-math',
    title: 'Counting to 3 with Manipulatives',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 1,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Count 1-3 objects with one-to-one correspondence; recognize quantities',
    biblicalConnection: 'God created the sun, moon, and stars (3 parts of day/night)',
    materials: ['Small objects (blocks, buttons, etc.)', 'Number cards 1-3', 'Worksheet', 'Manipulatives'],
    momTime: {
      duration: 10,
      script: `We're learning to COUNT! One, two, three. Let me give you some blocks. Here's ONE block. You hold it. Now here's TWO blocks. Count with me: one, two. Great! Now THREE blocks. One, two, THREE! You're counting! Let's count your blocks again. Point to each one as we count: one... two... three. Perfect!`,
      steps: [
        'Introduce counting 1-3 with enthusiasm',
        'Give child 1 block, say "one", child repeats',
        'Give child 2 blocks, count together pointing to each',
        'Give child 3 blocks, count together',
        'Have child count independently with support',
      ],
    },
    guidedPractice: {
      description: 'Adult counts while child points to each object. "You point, I count"',
      example: 'Adult puts 2 buttons down. Child points to each, adult says "one, two"',
    },
    independentActivity: {
      description: 'Child circles groups of 1, 2, 3 on worksheet; counts aloud',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Number Sense: Count to 3',
      fileUrl: '/worksheets/week-01/pre-k/Math_Count_to_3.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Counting Beyond',
      fileUrl: '/worksheets/week-01/pre-k/Challenge_Count_Beyond.pdf',
      description: 'Count to 5; compare more/fewer groups',
    },
    answerKey: 'Child circles correct quantities; counts aloud to verify',
    ifStruggling: 'Focus on 1 and 2 only. Use very concrete objects. Multiple practice days.',
    ifAdvanced: 'Count to 5 with same materials',
  },

  // Monday Kindergarten: Literacy
  {
    id: 'l-w1-mon-k-lit',
    title: 'Alphabet Sounds: /A/ and /I/',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 1,
    day: 'monday',
    gradeBand: 'k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Recognize and produce /a/ and /i/ sounds; match to letter forms A and I',
    biblicalConnection: 'God gave us words to speak and letters to write (Genesis 11:1-9 on language)',
    materials: ['Letter cards A and I', 'Picture cards (apple, ant, ice, igloo)', 'Letter formation guide'],
    momTime: {
      duration: 10,
      script: `Listen carefully. This is the /A/ sound. Say it with me: /A/ /A/ /A/. Can you hear it? Now listen to /I/: /I/ /I/ /I/. Great! Look at this letter—it's A. It makes the /A/ sound. And this is I. It makes the /I/ sound. Let me show you some pictures. APPLE starts with /A/. What sound does it start with? /A/! ICE starts with /I/. /I/! You're learning sounds!`,
      steps: [
        'Model /a/ sound with exaggerated mouth, have child repeat',
        'Model /i/ sound, have child repeat',
        'Show letter A, say sound together',
        'Show letter I, say sound together',
        'Show picture cards, child identifies beginning sound',
      ],
    },
    guidedPractice: {
      description: 'Adult shows picture, makes sound. Child repeats sound and tries to name picture.',
      example: 'Adult shows apple picture, says "/A/". Child repeats "/A/" and says "apple"',
    },
    independentActivity: {
      description: 'Child completes worksheet matching pictures to sounds',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Introduce: Alphabet Sounds /A/ and /I/',
      fileUrl: '/worksheets/week-01/k/Monday_Literacy_Phonics.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Decode CVC Word',
      fileUrl: '/worksheets/week-01/k/Challenge_Decode_CVC.pdf',
      description: 'Use known sounds to read unfamiliar CVC word',
    },
    answerKey: 'Circled pictures: apple, ant, ice, igloo (or similar /a/ and /i/ words)',
    ifStruggling: 'Focus on just /A/ for 2-3 days. Use real objects (apple). Add /I/ later.',
    ifAdvanced: 'Find /A/ and /I/ words around house',
  },

  // Monday Kindergarten: Math
  {
    id: 'l-w1-mon-k-math',
    title: 'Number Bonds & Decomposition (1-5)',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 1,
    day: 'monday',
    gradeBand: 'k',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Show different ways to make 3, 4, and 5 using manipulatives and pictures',
    biblicalConnection: 'God made creation with different parts that work together (Psalm 19:1)',
    materials: ['Counters or blocks', 'Ten-frames or circles on paper', 'Pictures showing decomposition'],
    momTime: {
      duration: 12,
      script: `Today we're finding DIFFERENT ways to make numbers. Watch: I have 5 blocks. I can make 5 this way: 3 blocks here, 2 blocks here. Three and two make five! Let me try again. This time: 4 blocks here, 1 block here. Four and one make five! Same number, different ways. Can YOU make five? Here are your 5 blocks. Try making it with different groups.`,
      steps: [
        'Show 5 blocks, separate into 3 + 2, say "three and two make five"',
        'Show same 5 blocks, separate into 4 + 1, say "four and one make five"',
        'Try with 4 blocks: 2 + 2, then 3 + 1',
        'Give child blocks to explore different combinations',
        'Record with pictures what they made',
      ],
    },
    guidedPractice: {
      description: 'Adult arranges blocks, child says the combination. Then child arranges, adult repeats.',
      example: 'Adult puts 2 blocks + 3 blocks. Child says "two and three make five"',
    },
    independentActivity: {
      description: 'Child uses blocks to show different ways to make 4 and 5; draws or records solutions',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Number Bonds: Ways to Make Numbers',
      fileUrl: '/worksheets/week-01/k/Math_Number_Bonds.pdf',
    },
    answerKey: 'For 5: 1+4, 2+3, 3+2, 4+1. For 4: 1+3, 2+2, 3+1',
    ifStruggling: 'Focus on 3 only: 1+2 and 2+1. Use concrete blocks, not pictures.',
    ifAdvanced: 'Show 6 and 7; find all combinations',
  },

  // Monday 1st Grade: Literacy
  {
    id: 'l-w1-mon-1st-lit',
    title: 'Consonant Digraph: /TH/ Sound',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 1,
    day: 'monday',
    gradeBand: '1st',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Identify and produce /th/ sound; recognize TH digraph in words',
    biblicalConnection: 'Words have power—we use our mouths to speak truth (Proverbs 31:26)',
    materials: ['Word list with /th/ words', 'Picture cards', 'Letter cards T and H'],
    momTime: {
      duration: 10,
      script: `Today we're learning a NEW sound: /TH/. It's made by TWO letters together: T and H. Listen: /TH/. Say it with me: /TH/. Feel your tongue between your teeth. /TH/. Here are some words that have this sound: THE, THAT, THIS, THINK, THREE, THANK YOU. Listen for the /TH/ sound. Say these with me: THE... THAT... THIS... THINK. You've got it!`,
      steps: [
        'Model /th/ sound, show tongue between teeth',
        'Have child repeat /th/ sound multiple times',
        'Say word list together: the, that, this, think, three',
        'Have child identify /th/ words in sentence: "I think the dog is there"',
        'Write TH letters, explain two letters make one sound (digraph)',
      ],
    },
    guidedPractice: {
      description: 'Adult says /th/ word, child repeats. Then child finds words in text.',
      example: 'Adult: "I say THINK. What sound is at the beginning?" Child: "/TH/"',
    },
    independentActivity: {
      description: 'Child decodes /th/ words; circles them in sentences',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Introduce: Digraph /TH/ Sound',
      fileUrl: '/worksheets/week-01/1st/Monday_Literacy_Digraph.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Digraph Application',
      fileUrl: '/worksheets/week-01/1st/Challenge_Digraph_Sentences.pdf',
      description: 'Write sentences using /th/ words; read unfamiliar passage',
    },
    answerKey: 'Words circled: the, that, this, think, three, thank. Sentences follow phonics rule.',
    ifStruggling: 'Use only 3-4 /th/ words. Practice sound in isolation daily.',
    ifAdvanced: 'Distinguish voiced /th/ (this, that) from unvoiced /th/ (think, thank)',
  },

  // Monday 1st Grade: Math
  {
    id: 'l-w1-mon-1st-math',
    title: 'Addition Strategies: Make 10',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 1,
    day: 'monday',
    gradeBand: '1st',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Use "make 10" strategy to solve addition facts efficiently',
    biblicalConnection: 'Jesus taught us to think wisely and find good solutions (Proverbs 3:21)',
    materials: ['Ten-frames', 'Counters', 'Number cards', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `Today we're learning a SMART way to add. It's called MAKE TEN. Watch: I have 8 + 4. That's a lot to count. But here's the trick: 8 is almost 10! I just need 2 more to make 10. Look at my 4—I can take 2 of those and give it to 8 to MAKE 10. Now I have 10 plus 2 left over. 10 and 2 make 12! So 8 + 4 = 12. Let's try another: 9 + 3. Make 10 first!`,
      steps: [
        'Show 8 on ten-frame (8 full, 2 empty)',
        'Show the 4 counters separately',
        'Identify: 8 needs 2 more to make 10',
        'Move 2 of the 4 counters to complete the ten-frame',
        'Count: 10 (full frame) + 2 (left over) = 12',
        'Practice with 9 + 3, 8 + 5, 7 + 4',
      ],
    },
    guidedPractice: {
      description: 'Adult shows problem on ten-frame. Child identifies how many more to make 10, then solves.',
      example: 'Adult: "I have 7. What do I add to make 10?" Child: "3." Adult: "Right! 7 + 3 = 10."',
    },
    independentActivity: {
      description: 'Child solves make-10 problems using ten-frames',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Introduction: Make 10 Strategy',
      fileUrl: '/worksheets/week-01/1st/Math_Make_10_Intro.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Multi-Step Problems',
      fileUrl: '/worksheets/week-01/1st/Challenge_Multi_Step_Math.pdf',
      description: 'Solve 2-3 step word problems using make-10 strategy',
    },
    answerKey: '8+4=12, 9+3=12, 7+5=12, 9+4=13, 8+5=13',
    ifStruggling: 'Use only 10-frame method. Practice 9 + 1, 8 + 2 repeatedly first.',
    ifAdvanced: 'Apply make-10 strategy to two-digit addition (23 + 8)',
  },
]

// ==================== WEEK 2: God Made Me & My Family ====================

const week2Lessons: Lesson[] = [
  // Pre-K Family theme
  {
    id: 'l-w2-mon-pre-k-lit',
    title: 'Family Members (Naming & Matching)',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 2,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 8,
    essential: true,
    owner: 'shared',
    learningObjective: 'Name family members; recognize family unit; letter M',
    biblicalConnection: 'God made families on purpose. Family is a gift (Genesis 2:22-24)',
    materials: ['Family picture cards', 'Letter M card', 'Worksheet'],
    momTime: {
      duration: 8,
      script: `God made YOUR family on purpose! Look at these pictures. This is a mommy. This is a daddy. This is a sister. This is a brother. Which one is in YOUR family? Let me tell you about your family. You have a mom and a dad. That's your family! The letter M is for MOM and MOMMY. Let's say it: M is for MOM.`,
      steps: [
        'Introduce family concept',
        'Show family pictures, name each role',
        'Discuss child's own family',
        'Connect to M for Mom',
        'Practice tracing M',
      ],
    },
    guidedPractice: {
      description: 'Show pictures, child names family members',
      example: 'Adult shows mom picture. Child says "mommy"',
    },
    independentActivity: {
      description: 'Match family pictures; color family portrait',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Introduce: Family Members',
      fileUrl: '/worksheets/week-02/pre-k/Monday_Literacy_Family.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Family Patterns',
      fileUrl: '/worksheets/week-02/pre-k/Challenge_Family_Patterns.pdf',
    },
    answerKey: 'Matched family pictures; colored family portrait showing all members',
    ifStruggling: 'Focus on 2 family roles only (mom, child)',
    ifAdvanced: 'Extend family: grandparents, aunts, uncles',
  },

  {
    id: 'l-w2-mon-pre-k-math',
    title: 'Count My Family (Grouping & Sorting)',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 2,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Count family members; understand groups; sort by attributes',
    biblicalConnection: 'God created us in His image and gave us families to belong to',
    materials: ['Family picture cards', 'Counters', 'Sorting circles'],
    momTime: {
      duration: 10,
      script: `Let's count YOUR family! How many people live with you? Let me count: one, two, three... That's your family group! Let's count mine: one, two, three, four. I have four. Look at these family cards. Girls are here (point), boys are here (point). We can sort them! This is grouping.`,
      steps: [
        'Count child's family members together',
        'Use counters to represent family',
        'Sort by: mom, dad, siblings, etc.',
        'Count each group',
        'Compare groups (more/fewer)',
      ],
    },
    guidedPractice: {
      description: 'Adult sorts one card, child sorts the next',
      example: 'Adult puts mom card in circle. Child puts sister card in circle.',
    },
    independentActivity: {
      description: 'Child sorts family cards by different attributes',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Count & Sort My Family',
      fileUrl: '/worksheets/week-02/pre-k/Math_Count_Families.pdf',
    },
    answerKey: 'Counting and grouping shown in worksheet; child's own family configuration',
    ifStruggling: 'Just count total family. Skip sorting for now.',
    ifAdvanced: 'Sort by multiple attributes (mom/dad, older/younger)',
  },

  // Kindergarten Week 2
  {
    id: 'l-w2-mon-k-lit',
    title: '/F/ and /M/ Beginning Sounds (Family theme)',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 2,
    day: 'monday',
    gradeBand: 'k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Recognize /f/ and /m/ sounds; connect to family words',
    biblicalConnection: 'Our mouths speak love to our family (Proverbs 31:26)',
    materials: ['Letter cards F and M', 'Picture cards (family, father, mother, fish)'],
    momTime: {
      duration: 10,
      script: `We learned M for MOM last week! Remember? /M/. Today we add /F/. Listen: /F/. That's the /F/ sound for FAMILY and FATHER! Say it: /F/ /F/. Here are words: FAMILY starts with /F/. What sound? /F/! MOTHER starts with /M/! FATHER starts with /F/!`,
      steps: [
        'Review M for Mom',
        'Introduce /f/ sound',
        'Practice /f/ and /m/ together',
        'Match sounds to family words',
        'Trace F and M letters',
      ],
    },
    guidedPractice: {
      description: 'Adult says family word, child identifies sound',
      example: 'Adult: "MOMMY." Child: "/M/"',
    },
    independentActivity: {
      description: 'Match family words to sounds on worksheet',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Introduce: /F/ & /M/ Sounds',
      fileUrl: '/worksheets/week-02/k/Monday_Literacy_FM_Sounds.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Create Own Word',
      fileUrl: '/worksheets/week-02/k/Challenge_Create_Word.pdf',
    },
    answerKey: 'Matched family, father, mother, fish to /f/ and /m/ sounds',
    ifStruggling: 'Focus only on /M/ sound this week',
    ifAdvanced: 'Find /f/ and /m/ words in read-aloud books',
  },

  {
    id: 'l-w2-mon-k-math',
    title: 'Comparing Quantities: More & Less',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 2,
    day: 'monday',
    gradeBand: 'k',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Compare two groups; identify more, less, equal',
    biblicalConnection: 'God gives us different amounts and teaches us to be grateful',
    materials: ['Counters', 'Number cards', 'Comparison pictures'],
    momTime: {
      duration: 12,
      script: `Let me show you something. Here are 5 blocks. Here are 2 blocks. Which group has MORE? That's right—5 blocks! Which group has LESS? 2 blocks! Let's use a cool symbol: > means MORE is on the left, < means LESS is on the left. 5 > 2. Say: "5 is MORE than 2."`,
      steps: [
        'Create two groups of different sizes',
        'Ask which is more/less',
        'Introduce > and < symbols informally',
        'Practice saying comparisons',
        'Have child create groups and compare',
      ],
    },
    guidedPractice: {
      description: 'Adult creates groups, child says more or less',
      example: 'Adult puts 3 and 4 blocks. Child: "3 is less, 4 is more"',
    },
    independentActivity: {
      description: 'Child circles larger group in multiple comparisons',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Comparing: More & Less',
      fileUrl: '/worksheets/week-02/k/Math_More_Less.pdf',
    },
    answerKey: 'Larger groups consistently circled; correct comparisons identified',
    ifStruggling: 'Use very different quantities first (1 vs 5)',
    ifAdvanced: 'Use 3-4 groups; order from least to most',
  },

  // 1st Grade Week 2
  {
    id: 'l-w2-mon-1st-lit',
    title: 'Vowel Teams: /OO/ Sound',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 2,
    day: 'monday',
    gradeBand: '1st',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Distinguish long /oo/ and short /oo/ sounds; read words with OO',
    biblicalConnection: 'Two letters working together make one sound—teamwork (1 Corinthians 12:12)',
    materials: ['Word cards with oo words', 'Picture cards (book, boot, moon, wood)'],
    momTime: {
      duration: 10,
      script: `Today we learn about TWO letters making ONE sound. Watch: O and O together = OO. But listen—there are TWO different /oo/ sounds! BOOK has the short /oo/ sound. Listen: /ook/. But MOON has the LONG /oo/ sound. Listen: /ooon/. Let me read some words: BOOT (long oo), WOOD (short oo). You try!`,
      steps: [
        'Introduce vowel team concept',
        'Model long /oo/ (moon, boot)',
        'Model short /oo/ (book, wood)',
        'Distinguish with picture cards',
        'Practice reading both types',
      ],
    },
    guidedPractice: {
      description: 'Adult says word, child identifies long or short oo',
      example: 'Adult: "BOOT." Child: "Long OO."',
    },
    independentActivity: {
      description: 'Sort OO words by long/short sound',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Introduce: Vowel Team /OO/',
      fileUrl: '/worksheets/week-02/1st/Monday_Literacy_OO_Team.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! OO Sound Discrimination',
      fileUrl: '/worksheets/week-02/1st/Challenge_OO_Reading.pdf',
    },
    answerKey: 'Long oo: moon, boot, food, cool. Short oo: book, foot, wood, look',
    ifStruggling: 'Focus only on long /oo/ (moon, boot) first',
    ifAdvanced: 'Distinguish from /u/ sound (cut); identify other vowel teams (ai, ea)',
  },

  {
    id: 'l-w2-mon-1st-math',
    title: 'Subtraction as Inverse of Addition',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 2,
    day: 'monday',
    gradeBand: '1st',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Understand subtraction as inverse of addition; connect related facts',
    biblicalConnection: 'God shows us how things are connected and work together',
    materials: ['Ten-frames', 'Counters', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `Watch something cool. I have 5 blocks. I add 2. Now I have 7. 5 + 2 = 7. Now watch: I have 7 blocks. I take AWAY 2. Now I have 5. 7 - 2 = 5. They're OPPOSITES! Addition and subtraction are friends! 5 + 2 = 7 and 7 - 2 = 5. They work together!`,
      steps: [
        'Show addition problem: 5 + 3 = 8',
        'Show subtraction going backward: 8 - 3 = 5',
        'Explain inverse relationship',
        'Try with 4 + 2 = 6 and 6 - 2 = 4',
        'Child creates related facts',
      ],
    },
    guidedPractice: {
      description: 'Adult shows addition on ten-frame. Child shows corresponding subtraction.',
      example: 'Adult: 6 + 1 = 7 on ten-frame. Child: "So 7 - 1 = 6"',
    },
    independentActivity: {
      description: 'Child writes related addition/subtraction facts',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Subtraction as Inverse',
      fileUrl: '/worksheets/week-02/1st/Math_Subtraction_Inverse.pdf',
    },
    answerKey: 'Related facts: 3+4=7 and 7-4=3; 5+2=7 and 7-2=5; etc.',
    ifStruggling: 'Focus on one related fact pair (5+3=8, 8-3=5) for a week',
    ifAdvanced: 'Extend to larger numbers (14 + 6 = 20, 20 - 6 = 14)',
  },
]

// ==================== WEEK 3: God's Care ====================

const week3Lessons: Lesson[] = [
  // Monday Pre-K: Literacy
  {
    id: 'l-w3-mon-pre-k-lit',
    title: 'God Cares for Me (Letter C)',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 3,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 8,
    essential: true,
    owner: 'shared',
    learningObjective: 'Recognize letter C; identify /k/ sound; understand God cares',
    biblicalConnection: 'God cares for us like a shepherd cares for sheep (Psalm 23:1)',
    materials: ['Picture cards of caring (hugging, holding, comforting)', 'Letter C card', 'Crayons', 'Worksheet'],
    momTime: {
      duration: 8,
      script: `Today we're learning about CARE. God cares for YOU. What does care look like? When Mom hugs you, that's care. When Dad listens to you, that's care. When someone holds your hand, that's care. Now we're learning the letter C. C is for CARE and CAT and CUDDLE. Let's make the /k/ sound together. /K/. The letter C makes the /k/ sound. C is for CARING!`,
      steps: [
        'Ask: "How does someone show you they care?"',
        'Show pictures of caring actions (hug, hold, comfort)',
        'Introduce letter C with /k/ sound',
        'Say words: care, cat, cuddle, come',
        'Trace C in air; draw yourself being cared for',
      ],
    },
    guidedPractice: {
      description: 'Teacher shows caring picture. Child names the action.',
      example: 'Teacher shows hug picture. Child: "Hug! That\'s care!"',
    },
    independentActivity: {
      description: 'Match caring actions to pictures; trace letter C',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'God Cares for Me (Letter C & Caring)',
      fileUrl: '/worksheets/week-03/pre-k/Monday_Literacy_Care.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Care Hunt',
      fileUrl: '/worksheets/week-03/pre-k/Challenge_Care_Words.pdf',
      description: 'Find and circle words that start with C sound in pictures',
    },
    answerKey: 'Matched: hug-hug, hold-hold, comfort-comfort. C traced correctly.',
    ifStruggling: 'Focus on matching action pictures only; skip C letter for now',
    ifAdvanced: 'Find objects around house that start with /k/ sound (cup, car, coat)',
  },

  // Monday Pre-K: Math
  {
    id: 'l-w3-mon-pre-k-math',
    title: 'Comparing Groups: More & Less',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 3,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Compare groups by quantity; use "more" and "less" accurately',
    biblicalConnection: 'God gives us what we need; gratitude for what we have',
    materials: ['Counters or blocks', 'Picture cards with groups', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `Today we're learning to COMPARE groups. I have 3 blocks here (show 3). And I have 1 block here (show 1). Which group has MORE? The one with 3 has MORE! Which has LESS? The one with 1 has LESS. MORE blocks are on this side. LESS blocks are on this side. Let's count: 1, 2, 3. More! Now count this: 1. Less! More means a bigger group. Less means a smaller group.`,
      steps: [
        'Create two groups (3 blocks and 1 block)',
        'Compare visually: "Which has more?"',
        'Count the larger group: "1, 2, 3—More!"',
        'Count the smaller group: "1—Less!"',
        'Repeat with different quantities (4 vs 2, 5 vs 1)',
      ],
    },
    guidedPractice: {
      description: 'Adult shows two groups. Child points to the one with more.',
      example: 'Adult shows 4 counters and 2 counters. Child: "This one has more!" (pointing to 4)',
    },
    independentActivity: {
      description: 'Compare picture groups; mark which has more/less',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Comparing Groups: More & Less',
      fileUrl: '/worksheets/week-03/pre-k/Math_More_Less.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Group Comparisons',
      fileUrl: '/worksheets/week-03/pre-k/Challenge_Compare_Groups.pdf',
      description: 'Compare three groups; order by quantity',
    },
    answerKey: 'Group 1 has more: 4>2, 5>3. Group 2 has less: 2<4, 3<5',
    ifStruggling: 'Use only 2 vs 1. Repeat daily with concrete objects.',
    ifAdvanced: 'Compare three groups; order from least to most',
  },

  // Monday Kindergarten: Literacy
  {
    id: 'l-w3-mon-k-lit',
    title: 'Beginning Sound /C/: Care, Can, Cat',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 3,
    day: 'monday',
    gradeBand: 'k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Identify /k/ sound and letter C; read beginning C words',
    biblicalConnection: 'God calls us by name and cares for us personally (Isaiah 43:1)',
    materials: ['Picture cards (car, cat, can, cake, cap)', 'Letter C card', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `Today we learn about the /K/ sound. Watch my mouth: /K/. This sound starts lots of words. The letter C makes this sound. Here are words that start with /K/: CAR, CAT, CAN, CAKE, CAP. Listen for /K/ at the beginning: /K/-ar. /K/-at. /K/-an. Now YOU say: CAR. CAT. CAN. Say /K/ with me. Now let's read: "The CAT can CAN." The C sound is special.`,
      steps: [
        'Model /k/ sound: /K/ (mouth open)',
        'Show picture cards: car, cat, can, cake, cap',
        'Say each word emphasizing /k/ beginning',
        'Child repeats each word',
        'Read sentence: "The cat can..." with /k/ words',
      ],
    },
    guidedPractice: {
      description: 'Adult shows picture. Child says the /C/ word.',
      example: 'Adult shows car picture. Child: "Car! /K/-ar."',
    },
    independentActivity: {
      description: 'Circle C words in pictures; read simple C sentences',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Beginning Sound /C/: Pictures & Words',
      fileUrl: '/worksheets/week-03/k/Monday_Literacy_C_Sound.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! /C/ Word Sentences',
      fileUrl: '/worksheets/week-03/k/Challenge_C_Sentences.pdf',
      description: 'Read and illustrate sentences with /C/ words',
    },
    answerKey: 'Circled C words: car, cat, can, cake, cap. Sentences read correctly.',
    ifStruggling: 'Practice /k/ sound isolation daily. Use only car, cat, can.',
    ifAdvanced: 'Introduce C sometimes sounds like /s/ (city, circle—optional for K)',
  },

  // Monday Kindergarten: Math
  {
    id: 'l-w3-mon-k-math',
    title: 'Comparison: Equal, More, & Less',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 3,
    day: 'monday',
    gradeBand: 'k',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Compare groups using equal, more, and less; use comparison symbols understanding',
    biblicalConnection: 'Fair and equal sharing is important (1 Corinthians 10:24)',
    materials: ['Counters, blocks, or manipulatives', 'Number comparison cards', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `We're learning to COMPARE. Watch: I have 3 blocks here (show 3). I have 3 blocks here (show 3). Are they the SAME? YES! They're EQUAL. 3 equals 3. Now look: 4 blocks here (show 4). 2 blocks here (show 2). Which has MORE? The 4 has more! 4 is more than 2. Now: 2 blocks here. 5 blocks here. Which is LESS? The 2 is less! 2 is less than 5. Equal means the same. More means bigger. Less means smaller.`,
      steps: [
        'Show two equal groups (3 and 3)',
        'Count both: "Are they equal?"',
        'Show unequal groups (4 and 2)',
        'Identify which has more',
        'Create different comparisons together',
      ],
    },
    guidedPractice: {
      description: 'Adult shows two groups. Child says if equal, more, or less.',
      example: 'Adult shows 5 vs 3. Child: "Five is more than three."',
    },
    independentActivity: {
      description: 'Compare groups on worksheet; write or circle more/less/equal',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Comparing Numbers: Equal, More, Less',
      fileUrl: '/worksheets/week-03/k/Math_Comparison.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Number Comparisons',
      fileUrl: '/worksheets/week-03/k/Challenge_Comparisons.pdf',
      description: 'Compare within 10; use comparison symbols',
    },
    answerKey: '3=3 (equal), 4>2 (more), 2<5 (less). All comparisons accurate.',
    ifStruggling: 'Use only concrete objects (blocks). Compare only 2 vs 1 first.',
    ifAdvanced: 'Introduce comparison symbols (>, <, =); compare within 10',
  },

  // Monday 1st Grade: Literacy
  {
    id: 'l-w3-mon-1st-lit',
    title: 'Sight Words & /C/ Blending: "I Care"',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 3,
    day: 'monday',
    gradeBand: '1st',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Read sight words (I, care, can) and /C/ blended words',
    biblicalConnection: 'Jesus teaches us to care for others (1 John 3:17-18)',
    materials: ['Word cards (I, care, can)', 'Picture cards of caring', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `We're reading words about CARE. First, a sight word: I. You see this everywhere. I. The letter I all by itself says "I." Now a word you can blend: CARE. Watch: /K/-ah-r. CARE. And CAN: /K/-ah-n. CAN. Now read these sentences: "I care." "I can." "I can care." You're reading! These are sentences about caring for others.`,
      steps: [
        'Show I card: "Sight word: I"',
        'Blend CARE: "/K/-ah-r... CARE"',
        'Blend CAN: "/K/-ah-n... CAN"',
        'Read sentence: "I care."',
        'Read sentence: "I can care."',
      ],
    },
    guidedPractice: {
      description: 'Adult says sight word or blend. Child reads it.',
      example: 'Adult points to CAN. Child: "/K/-ah-n... CAN"',
    },
    independentActivity: {
      description: 'Read I/care/can sentences; match to pictures of caring',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Sight Words & Blending: I Care',
      fileUrl: '/worksheets/week-03/1st/Monday_Literacy_I_Care.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Care Sentences',
      fileUrl: '/worksheets/week-03/1st/Challenge_Care_Reading.pdf',
      description: 'Read and write sentences using I, can, care, and /C/ words',
    },
    answerKey: 'Sight words: I (correct). Blended words: care, can (correct blending). Sentences read accurately.',
    ifStruggling: 'Focus on I (sight word) and CARE (blend). Skip CAN for now.',
    ifAdvanced: 'Write own sentences: "I care..." and "I can..."',
  },

  // Monday 1st Grade: Math
  {
    id: 'l-w3-mon-1st-math',
    title: 'Word Problems: Sharing & Caring',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 3,
    day: 'monday',
    gradeBand: '1st',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Solve addition/subtraction word problems with real-world context (sharing)',
    biblicalConnection: 'Generosity and sharing show God\'s love (2 Corinthians 9:7)',
    materials: ['Counters', 'Picture cards showing sharing', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `We're solving REAL problems today. Listen: Sarah has 5 apples. She wants to share with her sister. She gives 2 apples. How many apples does Sarah have now? Let's solve it together. Start with 5 (show 5 counters). Take away 2 (remove 2). Count what's left: 1, 2, 3. Sarah has 3 apples left. This is a REAL problem about caring and sharing! Let's try another: Tom has 4 toys. His friend gives him 3 more toys. How many does Tom have now? Start with 4. Add 3. Count: 1, 2, 3, 4, 5, 6, 7. Tom has 7 toys!`,
      steps: [
        'Read story problem aloud',
        'Act out with counters',
        'Identify: add or subtract?',
        'Solve with manipulatives',
        'Write number sentence: 5 - 2 = 3',
        'Check answer',
      ],
    },
    guidedPractice: {
      description: 'Teacher reads problem. Child solves with counters.',
      example: 'Teacher: "Maria has 3 crayons. She gets 2 more. How many?" Child shows 5 counters.',
    },
    independentActivity: {
      description: 'Solve 3-4 word problems with pictures; write number sentences',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Word Problems: Sharing & Caring',
      fileUrl: '/worksheets/week-03/1st/Math_Word_Problems_Sharing.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Multi-Step Sharing Problems',
      fileUrl: '/worksheets/week-03/1st/Challenge_Word_Problems.pdf',
      description: 'Solve 2-step word problems; write own sharing story',
    },
    answerKey: 'Sharing problems: 5-2=3, 4+3=7, 6-1=5. All number sentences correct.',
    ifStruggling: 'Use only addition (giving/sharing). Start with small numbers (within 5).',
    ifAdvanced: 'Two-step problems: "Maria has 3 apples. She gets 2 more. She shares 1. How many now?" (3+2-1=4)',
  },
]

// ==================== WEEK 4: Senses & Exploration ====================

const week4Lessons: Lesson[] = [
  {
    id: 'l-w4-mon-pre-k-lit',
    title: 'Five Senses (Letter S)',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 4,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 8,
    essential: true,
    owner: 'shared',
    learningObjective: 'Identify five senses; recognize letter S; explore sensory words',
    biblicalConnection: 'God gave us five senses to explore and enjoy His world (Psalm 119:18)',
    materials: ['Sensory items (lemon, flower, bell, soft fabric, cracker)', 'Letter S card', 'Crayons'],
    momTime: {
      duration: 8,
      script: `Today we're learning about our FIVE SENSES. God gave us eyes to SEE. Hold your nose—what do we SMELL with? Nose! Open your mouth—we TASTE. Touch this soft blanket—we TOUCH. Listen—we HEAR with our ears. Let's say our senses: SEE, HEAR, TASTE, TOUCH, SMELL. The letter S starts so many sense words! S is for SEE, SMELL, SOFT, and SOUND!`,
      steps: [
        'Name and point to five senses on body',
        'Demonstrate each sense (show toy, listen for sound, etc.)',
        'Introduce letter S with /s/ sound',
        'Say sense words that start with S',
        'Have child name things they sense',
      ],
    },
    guidedPractice: {
      description: 'Teacher points to sense. Child names it and names something they sense.',
      example: 'Teacher: "What do we see?" Child: "Eyes! I see a bird!"',
    },
    independentActivity: {
      description: 'Match senses to pictures; trace letter S',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Five Senses (Letter S & Body Parts)',
      fileUrl: '/worksheets/week-04/pre-k/Monday_Literacy_Senses.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Sense Hunt',
      fileUrl: '/worksheets/week-04/pre-k/Challenge_Sense_Hunt.pdf',
      description: 'Find pictures for each sense around the house',
    },
    answerKey: 'Five senses identified: eyes, ears, nose, tongue, hands. S traced correctly.',
    ifStruggling: 'Focus on two senses first: see and hear. Skip S letter.',
    ifAdvanced: 'Describe something using all five senses',
  },

  {
    id: 'l-w4-mon-pre-k-math',
    title: 'Sorting by Attributes: Size, Color, Texture',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 4,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Sort objects by one attribute (size, color, or texture)',
    biblicalConnection: 'God organized the world with order and beauty (Genesis 1:4, 1:9)',
    materials: ['Objects to sort (buttons, blocks, beans)', 'Picture cards', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `We're sorting things! Sorting means putting things that are the same together. Look at these buttons. Some are BIG. Some are small. Let's put the BIG ones here (pile left). Small ones here (pile right). Perfect! We sorted by SIZE. Now look at these blocks. Red ones here. Blue ones here. We sorted by COLOR! Sorting helps us organize and notice how things are different.`,
      steps: [
        'Show objects (mixed buttons, blocks)',
        'Identify attribute: "Are these big or small?"',
        'Create two piles by attribute',
        'Count and compare piles',
        'Try a new attribute (color, texture)',
      ],
    },
    guidedPractice: {
      description: 'Adult shows object. Child decides which pile it belongs in.',
      example: 'Adult: "This is a big button. Where does it go?" Child points to big pile.',
    },
    independentActivity: {
      description: 'Sort objects or pictures by given attribute',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Sorting by Size, Color & Texture',
      fileUrl: '/worksheets/week-04/pre-k/Math_Sorting.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Sort Two Ways',
      fileUrl: '/worksheets/week-04/pre-k/Challenge_Sorting_Two.pdf',
      description: 'Sort same objects by two different attributes',
    },
    answerKey: 'Size sort: 3 big, 2 small. Color sort: 4 red, 3 blue. Texture: 5 smooth, 2 rough',
    ifStruggling: 'Use only 2 objects per pile. Focus on one attribute (size or color).',
    ifAdvanced: 'Sort by two attributes at once; make predictions before sorting',
  },

  {
    id: 'l-w4-mon-k-lit',
    title: 'Beginning Sound /S/: See, Sit, Sun',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 4,
    day: 'monday',
    gradeBand: 'k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Identify /s/ sound and letter S; read beginning S words',
    biblicalConnection: 'God wants us to see His creation (Deuteronomy 4:29)',
    materials: ['Picture cards (sun, sit, see, smile, snake)', 'Letter S card', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `Today we learn the /S/ sound. Watch my mouth: /S/. This is a quiet sound. Listen: /S/. Now let's say words that start with /S/: SUN, SIT, SEE, SMILE, SNAKE. Hear the /S/ at the beginning? /S/-un. /S/-it. /S/-ee. The letter S makes this sound. Let's read a sentence: "I see the sun!" Do you hear the /S/ sounds?`,
      steps: [
        'Model /s/ sound with open mouth',
        'Show picture cards: sun, sit, see, smile, snake',
        'Say each word emphasizing /s/ sound',
        'Child repeats each word',
        'Read sentence with S words',
      ],
    },
    guidedPractice: {
      description: 'Adult shows picture. Child says the /S/ word.',
      example: 'Adult shows sun. Child: "Sun! /S/-un."',
    },
    independentActivity: {
      description: 'Circle S words in sentences; read simple passages',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Beginning Sound /S/: Pictures & Words',
      fileUrl: '/worksheets/week-04/k/Monday_Literacy_S_Sound.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! /S/ Sentences',
      fileUrl: '/worksheets/week-04/k/Challenge_S_Sentences.pdf',
      description: 'Read and illustrate sentences with /S/ words',
    },
    answerKey: 'Circled S words: sun, sit, see, smile, snake. Sentences read correctly.',
    ifStruggling: 'Practice /s/ sound isolation. Use only sun and sit.',
    ifAdvanced: 'Find S words around classroom (signs, labels, books)',
  },

  {
    id: 'l-w4-mon-k-math',
    title: 'Patterns: Extending AB Patterns',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 4,
    day: 'monday',
    gradeBand: 'k',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Recognize and extend simple AB patterns',
    biblicalConnection: 'God's creation has beautiful patterns and order (Psalm 19:1)',
    materials: ['Pattern blocks, beads, or pictures', 'Pattern strip template', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `Look at this pattern: RED, BLUE, RED, BLUE. What comes next? RED! It keeps repeating. This is an AB pattern: A is red, B is blue. Let's make a pattern together: big, small, big, small, big, small. What comes next? SMALL! Now a color pattern: yellow, purple, yellow, purple. What comes next? YELLOW! Patterns are fun because we can predict what's next!`,
      steps: [
        'Show AB pattern: red, blue, red, blue',
        'Identify: A = red, B = blue',
        'Ask: "What comes next?"',
        'Extend pattern together',
        'Create new pattern together',
      ],
    },
    guidedPractice: {
      description: 'Adult shows pattern. Child identifies next item.',
      example: 'Pattern: small, big, small, big, ___. Child: "Small!"',
    },
    independentActivity: {
      description: 'Complete patterns by adding missing items',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Patterns: Extending AB Patterns',
      fileUrl: '/worksheets/week-04/k/Math_Patterns.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Create Your Own Pattern',
      fileUrl: '/worksheets/week-04/k/Challenge_Patterns.pdf',
      description: 'Create and extend personal ABC patterns',
    },
    answerKey: 'Extended patterns: red, blue, RED; big, small, BIG; yellow, purple, YELLOW',
    ifStruggling: 'Use only two colors. Make pattern very obvious (big space between)',
    ifAdvanced: 'Create ABC patterns (three-part); predict multiple items ahead',
  },

  {
    id: 'l-w4-mon-1st-lit',
    title: 'Blending S Words & Sight Word "See"',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 4,
    day: 'monday',
    gradeBand: '1st',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Read sight word "see" and blend /S/ CVC words',
    biblicalConnection: 'Jesus said "Let the little children come to me" and he saw their value (Matthew 19:14)',
    materials: ['Word cards (see, sit, sun, sat)', 'Picture cards', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `Sight word: SEE. You use this word all the time: "I see a bird." Now we're blending words that start with /S/. Watch: /S/-it = SIT. /S/-un = SUN. /S/-at = SAT. Try: /S/-it. Good! Now read this sentence: "I see the sun." You're reading!`,
      steps: [
        'Show SEE card: sight word',
        'Blend SIT: "/S/-it"',
        'Blend SUN: "/S/-un"',
        'Blend SAT: "/S/-at"',
        'Read sentences: "I see the sun." "I sit."',
      ],
    },
    guidedPractice: {
      description: 'Adult says beginning. Child finishes blending.',
      example: 'Adult: "/S/-." Child: "...un. SUN."',
    },
    independentActivity: {
      description: 'Read see/sit/sun/sat sentences; match to pictures',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Sight Word "See" & Blending S Words',
      fileUrl: '/worksheets/week-04/1st/Monday_Literacy_See.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! See Sentences',
      fileUrl: '/worksheets/week-04/1st/Challenge_See_Reading.pdf',
      description: 'Write sentences using see, sit, sun, sat',
    },
    answerKey: 'Sight word: see (correct). Blended: sit, sun, sat. Sentences read accurately.',
    ifStruggling: 'Focus on SEE as sight word. Skip blending for now.',
    ifAdvanced: 'Write own sentences: "I see..."',
  },

  {
    id: 'l-w4-mon-1st-math',
    title: 'Measurement: Comparing Lengths',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 4,
    day: 'monday',
    gradeBand: '1st',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Compare lengths using non-standard units; use longer/shorter/equal language',
    biblicalConnection: 'God made things different sizes; we notice and appreciate differences',
    materials: ['Objects to measure (pencils, blocks, string)', 'Paper clips or unifix cubes', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `We're measuring how LONG things are! This pencil is LONG. This one is SHORT. Which is longer? This one! Now let's measure using paper clips. This pencil is 8 paper clips long. This one is 5 paper clips. Which is longer? The 8-paper-clip one! We can compare lengths and say things are longer, shorter, or about the same. Let's measure our arms. Who has longer arms?`,
      steps: [
        'Show two pencils of different lengths',
        'Ask: "Which is longer?"',
        'Measure first pencil with paper clips: count',
        'Measure second pencil: count',
        'Compare: "8 is longer than 5"',
        'Find and measure other objects',
      ],
    },
    guidedPractice: {
      description: 'Adult shows object. Child predicts longer/shorter, then measures.',
      example: 'Adult: "Is the pen longer than the crayon?" Child measures and reports.',
    },
    independentActivity: {
      description: 'Measure objects with paper clips or blocks; record lengths',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Measurement: Comparing Lengths',
      fileUrl: '/worksheets/week-04/1st/Math_Measurement.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Measure & Compare',
      fileUrl: '/worksheets/week-04/1st/Challenge_Measurement.pdf',
      description: 'Measure multiple objects; order from shortest to longest',
    },
    answerKey: 'Pencil 1: 8 units. Pencil 2: 5 units. Pencil 1 is longer by 3 units.',
    ifStruggling: 'Use only 2 objects. Measure with same-size blocks.',
    ifAdvanced: 'Measure with inches/cm; compare by subtraction (how many more?)',
  },
]

// ==================== WEEK 5: Animals ====================

const week5Lessons: Lesson[] = [
  {
    id: 'l-w5-mon-pre-k-lit',
    title: 'Animal Sounds & Names (Letter A)',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 5,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 8,
    essential: true,
    owner: 'shared',
    learningObjective: 'Name animals and their sounds; recognize letter A',
    biblicalConnection: 'God created all the animals and called them good (Genesis 1:25)',
    materials: ['Animal pictures', 'Letter A card', 'Animal sound recording (optional)', 'Crayons'],
    momTime: {
      duration: 8,
      script: `What sounds do animals make? A DOG says WOOF WOOF! A CAT says MEOW! A COW says MOO! A DUCK says QUACK! Let's do all the sounds together! Now we're learning letter A. A is for ANIMAL! Can you say /A/? /A/! Listen: Apple, Apple, Ant—they all have the /A/ sound. Let's make animal sounds and trace letter A!`,
      steps: [
        'Show animal picture, make sound together',
        'Repeat with 4-5 different animals',
        'Introduce letter A with /a/ sound',
        'Say A words: apple, ant, animal',
        'Trace A in the air',
      ],
    },
    guidedPractice: {
      description: 'Teacher shows animal. Child makes sound and names it.',
      example: 'Teacher shows cow picture. Child: "MOO! Cow!"',
    },
    independentActivity: {
      description: 'Match animal sounds to pictures; trace letter A',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Animal Sounds & Letter A',
      fileUrl: '/worksheets/week-05/pre-k/Monday_Literacy_Animals.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Animal Hunt',
      fileUrl: '/worksheets/week-05/pre-k/Challenge_Animal_Sounds.pdf',
      description: 'Match sounds to animals; find A words',
    },
    answerKey: 'Sounds matched correctly. Letter A traced. Animal drawings identifiable.',
    ifStruggling: 'Focus on 2 animals (dog, cat). Skip letter A.',
    ifAdvanced: 'Describe what animals eat and where they live',
  },

  {
    id: 'l-w5-mon-pre-k-math',
    title: 'Counting & Grouping Animals',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 5,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Count objects within 10; group animals by type',
    biblicalConnection: 'Noah counted the animals carefully (Genesis 7:14-15)',
    materials: ['Animal pictures or toys', 'Picture cards', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `We have some animals here. Let's count the dogs: 1, 2, 3 dogs. Let's count the cats: 1, 2 cats. Which group has more? The 3 dogs have more! Now put all the animals together. Let's count: 1, 2, 3, 4, 5 animals! Five animals in all. We can sort animals: dogs together, cats together, birds together. Let's sort!`,
      steps: [
        'Show mixed animal pictures',
        'Count one type: "1, 2, 3 dogs"',
        'Count another type: "1, 2 cats"',
        'Separate animals into groups',
        'Count total',
      ],
    },
    guidedPractice: {
      description: 'Teacher shows animals. Child counts and groups.',
      example: 'Teacher: "How many dogs?" Child counts: "1, 2, 3."',
    },
    independentActivity: {
      description: 'Count and group animals on worksheet',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Counting & Grouping Animals',
      fileUrl: '/worksheets/week-05/pre-k/Math_Count_Animals.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Animal Groups',
      fileUrl: '/worksheets/week-05/pre-k/Challenge_Group_Animals.pdf',
      description: 'Count and compare animal groups',
    },
    answerKey: '3 dogs, 2 cats, 4 birds. Groups sorted correctly. Total counts accurate.',
    ifStruggling: 'Use only 2 types of animals. Count within 5.',
    ifAdvanced: 'Create bar graph of animal counts',
  },

  {
    id: 'l-w5-mon-k-lit',
    title: 'Beginning Sound /A/: Apple, Ant, Angry',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 5,
    day: 'monday',
    gradeBand: 'k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Identify /a/ sound and letter A; read beginning A words',
    biblicalConnection: 'All creatures are precious to God (Proverbs 12:10)',
    materials: ['Picture cards (apple, ant, angry, ape, alligator)', 'Letter A card', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `Today we learn the /A/ sound. Watch my mouth—it's wide open: /A/. Now let's say words that start with /A/: APPLE, ANT, ANGRY, APE, ALLIGATOR. Hear the /A/? /A/-pple. /A/-nt. /A/-ngry. The letter A makes this sound at the beginning of words. Let's read: "An apple and an ant." You did it!`,
      steps: [
        'Model /a/ sound with wide mouth',
        'Show picture cards and say words',
        'Have child repeat each word',
        'Identify /a/ at beginning',
        'Read simple A sentences',
      ],
    },
    guidedPractice: {
      description: 'Adult shows picture. Child says the /A/ word.',
      example: 'Adult shows apple. Child: "Apple! /A/-pple."',
    },
    independentActivity: {
      description: 'Circle A words; read sentences',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Beginning Sound /A/: Pictures & Words',
      fileUrl: '/worksheets/week-05/k/Monday_Literacy_A_Sound.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! /A/ Sentences',
      fileUrl: '/worksheets/week-05/k/Challenge_A_Sentences.pdf',
      description: 'Read and illustrate sentences with /A/ words',
    },
    answerKey: 'Circled A words: apple, ant, angry, ape, alligator. Sentences read correctly.',
    ifStruggling: 'Practice /a/ sound. Use only apple and ant.',
    ifAdvanced: 'Distinguish /a/ from other short vowels',
  },

  {
    id: 'l-w5-mon-k-math',
    title: 'Animal Counting & 1:1 Correspondence',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 5,
    day: 'monday',
    gradeBand: 'k',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Count to 20 with 1:1 correspondence; count animal groups',
    biblicalConnection: 'God knows every animal by name (Psalm 147:4)',
    materials: ['Animal pictures or counters', 'Number cards 1-20', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `We're counting animals up to 20! Let's count the sheep: 1 sheep, 2 sheep, 3 sheep... all the way to 10! Now we have more animals. Let's count to 20. We touch each one as we count—1, 2, 3... This is called one-to-one correspondence. We touch one animal for each number we say. Let's count these birds together!`,
      steps: [
        'Show animals in a group',
        'Count, touching each one',
        'Count again to verify',
        'Count up to 20 with different animals',
        'Practice 1:1 correspondence',
      ],
    },
    guidedPractice: {
      description: 'Adult shows animals. Child counts touching each one.',
      example: 'Adult: "Count these animals." Child: "1, 2, 3, 4, 5." (touching each)',
    },
    independentActivity: {
      description: 'Count animals on worksheet; write or record numbers',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Counting Animals to 20',
      fileUrl: '/worksheets/week-05/k/Math_Count_20_Animals.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Animal Count & Compare',
      fileUrl: '/worksheets/week-05/k/Challenge_Count_Compare.pdf',
      description: 'Count animal groups and compare (more/less/equal)',
    },
    answerKey: 'Counts accurate to 20. 1:1 correspondence shown. Comparisons correct.',
    ifStruggling: 'Count only to 10. Use larger, spaced-out images.',
    ifAdvanced: 'Skip count by 2s or 5s with animals',
  },

  {
    id: 'l-w5-mon-1st-lit',
    title: 'Reading A-Sound Words & Blending',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 5,
    day: 'monday',
    gradeBand: '1st',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Blend CVC words with short /a/ sound; read animal words',
    biblicalConnection: 'We care for God's animals with gentleness (Proverbs 12:10)',
    materials: ['Word cards (cat, bat, sat, mat, hat)', 'Picture cards', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `We're blending words with the /A/ sound today! Listen: /c/-/a/-/t/ = CAT. Let's try: /b/-/a/-/t/ = BAT. /s/-/a/-/t/ = SAT. /m/-/a/-/t/ = MAT. /h/-/a/-/t/ = HAT. All these words have the /A/ sound in the middle! Now read this sentence: "The cat sat on the mat." Do you hear all the /A/ sounds?`,
      steps: [
        'Sound out: /c/-/a/-/t/... CAT',
        'Blend: /b/-/a/-/t/... BAT',
        'Continue with sat, mat, hat',
        'Read sentences: "The cat sat."',
        'Match words to pictures',
      ],
    },
    guidedPractice: {
      description: 'Adult shows word. Child blends sounds.',
      example: 'Adult: "c-a-t?" Child: "/c/-/a/-/t/... CAT!"',
    },
    independentActivity: {
      description: 'Blend A-sound CVC words; read sentences',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Blending: Short /A/ Words',
      fileUrl: '/worksheets/week-05/1st/Monday_Literacy_A_Blending.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! /A/ Word Sentences',
      fileUrl: '/worksheets/week-05/1st/Challenge_A_Words.pdf',
      description: 'Write sentences using a-sound words',
    },
    answerKey: 'Blended words: cat, bat, sat, mat, hat (all correct). Sentences accurate.',
    ifStruggling: 'Focus on cat, bat, sat. Slow down blending.',
    ifAdvanced: 'Introduce a-sound words in sentences (The mat was black)',
  },

  {
    id: 'l-w5-mon-1st-math',
    title: 'Addition & Subtraction: Animals in Groups',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 5,
    day: 'monday',
    gradeBand: '1st',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Solve addition/subtraction word problems with animals',
    biblicalConnection: 'We care for animals by helping them (Proverbs 27:12)',
    materials: ['Animal pictures or counters', 'Ten-frames', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `We have a fun animal problem! There are 3 cats. 2 more cats come. How many cats are there now? Let's use our counters. Start with 3 (show 3). Add 2 (add 2 more). Count: 1, 2, 3, 4, 5. We have 5 cats! That's 3 + 2 = 5. Now: There are 6 dogs. 1 dog runs away. How many are left? Start with 6. Take away 1. Count: 1, 2, 3, 4, 5. We have 5 left. That's 6 - 1 = 5. Animals help us practice math!`,
      steps: [
        'Read problem: "3 cats + 2 cats"',
        'Show with counters',
        'Act it out',
        'Count total',
        'Write number sentence: 3 + 2 = 5',
        'Repeat with subtraction',
      ],
    },
    guidedPractice: {
      description: 'Teacher reads problem. Child solves with manipulatives.',
      example: 'Teacher: "4 birds + 2 birds = ?" Child shows 6 counters.',
    },
    independentActivity: {
      description: 'Solve animal word problems with pictures',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Word Problems: Animals',
      fileUrl: '/worksheets/week-05/1st/Math_Animal_Problems.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Animal Math Stories',
      fileUrl: '/worksheets/week-05/1st/Challenge_Animal_Math.pdf',
      description: 'Write and solve own animal word problems',
    },
    answerKey: '3+2=5, 6-1=5, 4+3=7, 8-2=6. All problems solved correctly.',
    ifStruggling: 'Use only addition. Use numbers within 5.',
    ifAdvanced: 'Two-step animal problems (Start with 5, add 2, take away 1)',
  },
]

// ==================== WEEK 6: Habitats ====================

const week6Lessons: Lesson[] = [
  {
    id: 'l-w6-mon-pre-k-lit',
    title: 'Where Animals Live (Letter H)',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 6,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 8,
    essential: true,
    owner: 'shared',
    learningObjective: 'Name habitats; recognize letter H and /h/ sound',
    biblicalConnection: 'God provides a home for every creature (Psalm 84:3)',
    materials: ['Habitat pictures (forest, ocean, desert, sky)', 'Letter H card', 'Crayons'],
    momTime: {
      duration: 8,
      script: `Where do animals live? A FISH lives in the WATER. A BIRD lives in a TREE. A BEAR lives in the FOREST. A SNAKE lives in the DESERT. Every animal has a HOME! We're learning the letter H. H is for HOME and HABITAT. Listen: /H/. House, Hat, Happy—they all start with /H/. Let's trace H in the air! H is for HOME.`,
      steps: [
        'Show habitat pictures one by one',
        'Name habitat: forest, water, desert',
        'Name animal in each habitat',
        'Introduce letter H with /h/ sound',
        'Say H words: home, hat, happy, house',
      ],
    },
    guidedPractice: {
      description: 'Teacher shows animal. Child names habitat.',
      example: 'Teacher shows fish picture. Child: "Water!"',
    },
    independentActivity: {
      description: 'Match animals to habitats; trace letter H',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Animal Habitats (Letter H)',
      fileUrl: '/worksheets/week-06/pre-k/Monday_Literacy_Habitats.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Habitat Hunt',
      fileUrl: '/worksheets/week-06/pre-k/Challenge_Habitats.pdf',
      description: 'Draw or find animals in their habitats',
    },
    answerKey: 'Habitats matched: fish-water, bird-tree, bear-forest. H traced correctly.',
    ifStruggling: 'Focus on 2 habitats: water and forest. Skip letter H.',
    ifAdvanced: 'Describe what makes each habitat special',
  },

  {
    id: 'l-w6-mon-pre-k-math',
    title: 'Patterning: Animal Repetition',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 6,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Create and extend simple animal patterns',
    biblicalConnection: 'God's creatures show amazing patterns in nature',
    materials: ['Animal pictures or toys', 'Pattern cards', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `We're making patterns with animals! Look: Dog, cat, dog, cat, dog, cat. What comes next? DOG! It's a pattern. Now: Bird, bird, fish, bird, bird, fish. What's next? BIRD! Patterns repeat. Let's make our own pattern: dog, dog, cat, dog, dog, cat. It repeats! Can you see it?`,
      steps: [
        'Show animal pattern: dog, cat, dog, cat',
        'Ask: "What comes next?"',
        'Identify the pattern (AB)',
        'Extend together',
        'Create new pattern with different animals',
      ],
    },
    guidedPractice: {
      description: 'Teacher shows partial pattern. Child completes.',
      example: 'Pattern: bird, fish, bird, fish, ___. Child: "Bird!"',
    },
    independentActivity: {
      description: 'Complete animal patterns on worksheet',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Animal Patterns',
      fileUrl: '/worksheets/week-06/pre-k/Math_Animal_Patterns.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Pattern Creator',
      fileUrl: '/worksheets/week-06/pre-k/Challenge_Create_Patterns.pdf',
      description: 'Create own animal patterns for others to continue',
    },
    answerKey: 'Patterns extended correctly: dog, dog, DOG; fish, cat, FISH; etc.',
    ifStruggling: 'Use only 2 animals. Make pattern very obvious.',
    ifAdvanced: 'Create 3-animal (ABC) patterns',
  },

  {
    id: 'l-w6-mon-k-lit',
    title: 'Beginning Sound /H/: House, Hat, Happy',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 6,
    day: 'monday',
    gradeBand: 'k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Identify /h/ sound; read beginning H words',
    biblicalConnection: 'God is our shelter and protection (Psalm 46:5)',
    materials: ['Picture cards (house, hat, happy, hand, horse)', 'Letter H card', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `Today we learn /H/. Watch my mouth—feel the air: /H/. Now say: /H/. Here are words: HOUSE, HAT, HAPPY, HAND, HORSE. Listen for /H/: /H/-ouse. /H/-at. /H/-appy. /H/-and. /H/-orse. Now read: "A happy horse in a house." You did it!`,
      steps: [
        'Model /h/ sound, feel breath',
        'Show picture cards and say words',
        'Have child repeat',
        'Identify /h/ at beginning',
        'Read simple H sentences',
      ],
    },
    guidedPractice: {
      description: 'Adult shows picture. Child says /H/ word.',
      example: 'Adult shows house. Child: "House! /H/-ouse."',
    },
    independentActivity: {
      description: 'Circle H words; read sentences',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Beginning Sound /H/: Pictures & Words',
      fileUrl: '/worksheets/week-06/k/Monday_Literacy_H_Sound.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! /H/ Sentences',
      fileUrl: '/worksheets/week-06/k/Challenge_H_Sentences.pdf',
      description: 'Read and illustrate sentences with /H/ words',
    },
    answerKey: 'Circled H words: house, hat, happy, hand, horse. Sentences correct.',
    ifStruggling: 'Practice /h/ sound. Use only house and hat.',
    ifAdvanced: 'Find H words around classroom',
  },

  {
    id: 'l-w6-mon-k-math',
    title: 'Number Sense: Subitizing to 5',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 6,
    day: 'monday',
    gradeBand: 'k',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Recognize quantities 1-5 without counting (subitizing)',
    biblicalConnection: 'God sees and knows everything (Psalm 139:1-2)',
    materials: ['Dot cards or animal pictures', 'Counters', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `Fast game! I'm going to show you some animals QUICK (flash 3 animals). How many did you see? THREE! You knew it without counting! This is called subitizing—seeing how many things are there without counting. Watch: (flash 5). Five! (flash 2). Two! You're getting fast! Let's practice with different amounts: 1, 2, 3, 4, 5.`,
      steps: [
        'Flash 1 animal briefly',
        'Ask: "How many?"',
        'Child says number (no counting)',
        'Show more examples (2, 3, 4, 5)',
        'Gradually increase speed',
      ],
    },
    guidedPractice: {
      description: 'Teacher flashes animals. Child says quantity.',
      example: 'Flash 4 animals. Child: "Four!"',
    },
    independentActivity: {
      description: 'Subitize quantities on worksheet',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Subitizing: Quick Quantity Recognition',
      fileUrl: '/worksheets/week-06/k/Math_Subitizing.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Fast Number Recognition',
      fileUrl: '/worksheets/week-06/k/Challenge_Subitizing.pdf',
      description: 'Recognize larger quantities (6-10) without counting',
    },
    answerKey: 'All quantities correctly identified without counting.',
    ifStruggling: 'Start with 1-3 only. Show for longer (not as quick flash).',
    ifAdvanced: 'Increase speed; recognize up to 10',
  },

  {
    id: 'l-w6-mon-1st-lit',
    title: 'Reading H-Sound Words & Blending',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 6,
    day: 'monday',
    gradeBand: '1st',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Blend CVC words with /h/ and review blending',
    biblicalConnection: 'Our home in God's house is safe (Psalm 27:5)',
    materials: ['Word cards (hat, has, hit, hop)', 'Picture cards', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `Blending time! Let's sound out: /h/-/a/-/t/ = HAT. /h/-/i/-/t/ = HIT. /h/-/o/-/p/ = HOP. Now read: "The hat has hops." Wait—that doesn't make sense! Let's try: "The cat can hop." Now it makes sense! We blend, we read, we check if it makes sense!`,
      steps: [
        'Sound out: /h/-/a/-/t/... HAT',
        'Blend: /h/-/i/-/t/... HIT',
        'Blend: /h/-/o/-/p/... HOP',
        'Read sentences',
        'Check for meaning',
      ],
    },
    guidedPractice: {
      description: 'Adult shows word. Child blends.',
      example: 'Adult: "h-a-t?" Child: "/h/-/a/-/t/... HAT!"',
    },
    independentActivity: {
      description: 'Blend H-sound words; read sentences',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Blending: /H/ Words',
      fileUrl: '/worksheets/week-06/1st/Monday_Literacy_H_Blending.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! /H/ Word Stories',
      fileUrl: '/worksheets/week-06/1st/Challenge_H_Words.pdf',
      description: 'Write sentences using h-sound words',
    },
    answerKey: 'Blended words: hat, hit, hop, has. Sentences accurate and meaningful.',
    ifStruggling: 'Focus on hat and hit. Slow down blending.',
    ifAdvanced: 'Read multi-syllable words: happy, hobby',
  },

  {
    id: 'l-w6-mon-1st-math',
    title: 'Place Value: Tens & Ones Introduction',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 6,
    day: 'monday',
    gradeBand: '1st',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Understand tens and ones; represent numbers 10-20',
    biblicalConnection: 'God's design shows order and structure everywhere',
    materials: ['Ten-frame', 'Counters or blocks', 'Bundle straws', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `We're learning about TENS and ONES! Look at this ten-frame. When it's full, we have ONE ten! Look: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. One full ten! Now if I add more: we have one ten (full frame) and 3 more. That's 1 ten and 3 ones = 13! Let's write 13. Watch as I make 13 with blocks. One group of 10 and 3 left over. Let's count: 10, 11, 12, 13!`,
      steps: [
        'Fill ten-frame to show one ten',
        'Add ones: show 10 + 1, 10 + 2, etc.',
        'Count from 10: "10, 11, 12, 13"',
        'Write the number',
        'Represent with blocks',
      ],
    },
    guidedPractice: {
      description: 'Teacher shows ten and ones. Child counts and tells the number.',
      example: 'Teacher shows full ten-frame + 4 ones. Child: "10, 11, 12, 13, 14. That\'s 14."',
    },
    independentActivity: {
      description: 'Represent numbers 10-20 with tens and ones',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Place Value: Tens & Ones',
      fileUrl: '/worksheets/week-06/1st/Math_Place_Value.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Building Numbers',
      fileUrl: '/worksheets/week-06/1st/Challenge_Place_Value.pdf',
      description: 'Represent and decompose numbers to 20',
    },
    answerKey: '10=1 ten, 13=1 ten 3 ones, 17=1 ten 7 ones. All representations correct.',
    ifStruggling: 'Use only 10-15. Represent with concrete blocks first.',
    ifAdvanced: 'Decompose numbers multiple ways (14 = 1 ten + 4 ones = 7 + 7)',
  },
]

// ==================== WEEK 7: Growth & Change ====================

const week7Lessons: Lesson[] = [
  {
    id: 'l-w7-mon-pre-k-lit',
    title: 'Growing Up (Letter G)',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 7,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 8,
    essential: true,
    owner: 'shared',
    learningObjective: 'Understand growth concept; recognize letter G',
    biblicalConnection: 'Jesus grew in wisdom and stature (Luke 2:52)',
    materials: ['Photos of growth (baby→child), plants', 'Letter G card', 'Crayons'],
    momTime: {
      duration: 8,
      script: `You're growing! Look how tall you are! When you were a baby, you were tiny like this (show small space). Now you're much bigger! GROW means to get bigger and stronger. Plants grow too. Look at this seed. It grows into a flower. We're learning letter G. G is for GROW and GARDEN and GREAT! Let's trace G!`,
      steps: [
        'Show before/after photos of child or plant',
        'Discuss growth: "How have you grown?"',
        'Introduce letter G with /g/ sound',
        'Say G words: grow, great, garden',
        'Trace G in air',
      ],
    },
    guidedPractice: {
      description: 'Teacher shows growth picture. Child identifies what grew.',
      example: 'Teacher shows plant photo. Child: "It grew bigger!"',
    },
    independentActivity: {
      description: 'Draw how you've grown; trace letter G',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Growing Up (Letter G)',
      fileUrl: '/worksheets/week-07/pre-k/Monday_Literacy_Growth.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Growth Chart',
      fileUrl: '/worksheets/week-07/pre-k/Challenge_Growth.pdf',
      description: 'Draw stages of growth (baby, child, adult)',
    },
    answerKey: 'Growth pictures correctly labeled. Letter G traced. Drawings show progression.',
    ifStruggling: 'Focus on baby vs. child only. Skip letter G.',
    ifAdvanced: 'Describe changes in plants, animals, family members',
  },

  {
    id: 'l-w7-mon-pre-k-math',
    title: 'Size Comparison: Small, Medium, Large',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 7,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Classify objects by size; use small, medium, large vocabulary',
    biblicalConnection: 'God appreciates all sizes and stages of growth (1 Peter 3:7)',
    materials: ['Objects of different sizes (balls, blocks, boxes)', 'Picture cards', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `We have three sizes: SMALL, MEDIUM, and LARGE. Look at these balls. This one is SMALL (show tiny ball). This one is MEDIUM (medium ball). This one is LARGE (big ball). Let's put them in order: small, medium, large! Now look at these boxes. Which is small? Medium? Large? Let's sort them!`,
      steps: [
        'Show three sizes of one object',
        'Name: small, medium, large',
        'Have child arrange by size',
        'Find objects around room to sort',
        'Order from smallest to largest',
      ],
    },
    guidedPractice: {
      description: 'Adult shows size. Child places in correct spot.',
      example: 'Adult: "This block is medium. Where does it go?" Child places it.',
    },
    independentActivity: {
      description: 'Sort objects or pictures by size',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Size Comparison: Small, Medium, Large',
      fileUrl: '/worksheets/week-07/pre-k/Math_Sizes.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Order by Size',
      fileUrl: '/worksheets/week-07/pre-k/Challenge_Order_Sizes.pdf',
      description: 'Order multiple objects from smallest to largest',
    },
    answerKey: 'Objects sorted correctly. Order: small, medium, large (smallest to largest).',
    ifStruggling: 'Use only small and large (skip medium).',
    ifAdvanced: 'Order 5+ objects by size; use comparative language (smaller, smallest)',
  },

  {
    id: 'l-w7-mon-k-lit',
    title: 'Beginning Sound /G/: Go, Good, Green',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 7,
    day: 'monday',
    gradeBand: 'k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Identify /g/ sound; read beginning G words',
    biblicalConnection: 'God is good and His creation is good (Genesis 1:31)',
    materials: ['Picture cards (go, good, green, girl, gift)', 'Letter G card', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `Today we learn /G/. Listen: /G/. Now say with me: /G/. Here are words: GO, GOOD, GREEN, GIRL, GIFT. Hear the /G/ at the start? /G/-o, /G/-ood, /G/-reen, /G/-irl. Let's read a sentence: "The good girl can go." You did it!`,
      steps: [
        'Model /g/ sound (hard G)',
        'Show picture cards: go, good, green, girl, gift',
        'Say each emphasizing /g/ sound',
        'Child repeats',
        'Read simple G sentences',
      ],
    },
    guidedPractice: {
      description: 'Adult shows picture. Child says /G/ word.',
      example: 'Adult shows green. Child: "Green! /G/-reen."',
    },
    independentActivity: {
      description: 'Circle G words; read sentences',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Beginning Sound /G/: Pictures & Words',
      fileUrl: '/worksheets/week-07/k/Monday_Literacy_G_Sound.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! /G/ Sentences',
      fileUrl: '/worksheets/week-07/k/Challenge_G_Sentences.pdf',
      description: 'Read and illustrate sentences with /G/ words',
    },
    answerKey: 'Circled G words: go, good, green, girl, gift. Sentences read correctly.',
    ifStruggling: 'Practice /g/ sound. Use only go and good.',
    ifAdvanced: 'Distinguish hard G from soft G (giant) — challenge for later',
  },

  {
    id: 'l-w7-mon-k-math',
    title: 'Adding Within 5: Real Objects',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 7,
    day: 'monday',
    gradeBand: 'k',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Solve addition problems within 5 using concrete objects',
    biblicalConnection: 'God adds blessings to our lives (Psalm 65:11)',
    materials: ['Counters, blocks, or objects', 'Picture cards', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `We're ADDING! I have 2 counters here (show 2). I have 1 more counter (add 1). Now how many? Count with me: 1, 2, 3. We have 3! 2 + 1 = 3. Again: I have 3 counters (show 3). I add 2 more (add 2). Count: 1, 2, 3, 4, 5. We have 5! 3 + 2 = 5. Let's try: 4 + 1. Show me with your counters!`,
      steps: [
        'Show first group of counters (2)',
        'Add second group (1)',
        'Count total together',
        'Write number sentence: 2 + 1 = 3',
        'Repeat with different amounts',
      ],
    },
    guidedPractice: {
      description: 'Adult gives amounts. Child shows and counts total.',
      example: 'Adult: "Show 1 plus 2." Child: "1, 2, 3. That\'s 3."',
    },
    independentActivity: {
      description: 'Add using objects within 5',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Adding Within 5',
      fileUrl: '/worksheets/week-07/k/Math_Adding_5.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Adding Stories',
      fileUrl: '/worksheets/week-07/k/Challenge_Adding_Stories.pdf',
      description: 'Create addition stories with objects',
    },
    answerKey: '2+1=3, 3+2=5, 4+1=5, 3+1=4. All sums within 5 correct.',
    ifStruggling: 'Use only 1+1, 2+1, 1+2. Use concrete counters only.',
    ifAdvanced: 'Add within 10; write number sentences independently',
  },

  {
    id: 'l-w7-mon-1st-lit',
    title: 'Blending G Words & Reading Sentences',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 7,
    day: 'monday',
    gradeBand: '1st',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Blend CVC words with /g/; read sentences',
    biblicalConnection: 'God's word guides us (Psalm 119:105)',
    materials: ['Word cards (go, gap, got, gas)', 'Picture cards', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `Let's blend words with /G/. Watch: /g/-/o/ = GO. /g/-/a/-/p/ = GAP. /g/-/o/-/t/ = GOT. /g/-/a/-/s/ = GAS. Now read: "Go, go, go!" "The cat got a gap." Let's read more sentences with /G/ words!`,
      steps: [
        'Sound out: /g/-/o/... GO',
        'Blend: /g/-/a/-/p/... GAP',
        'Continue with got, gas',
        'Read sentences',
        'Match to pictures',
      ],
    },
    guidedPractice: {
      description: 'Adult says sounds. Child finishes blending.',
      example: 'Adult: "/g/-/o/?" Child: "...GO!"',
    },
    independentActivity: {
      description: 'Blend G words; read sentences',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Blending: G Words',
      fileUrl: '/worksheets/week-07/1st/Monday_Literacy_G_Blending.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! G Word Stories',
      fileUrl: '/worksheets/week-07/1st/Challenge_G_Words.pdf',
      description: 'Write sentences using g-sound words',
    },
    answerKey: 'Blended words: go, gap, got, gas (all correct). Sentences accurate.',
    ifStruggling: 'Focus on go and got. Slow down blending.',
    ifAdvanced: 'Read longer words: going, getting',
  },

  {
    id: 'l-w7-mon-1st-math',
    title: 'Subtraction Facts Within 10',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 7,
    day: 'monday',
    gradeBand: '1st',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Solve subtraction problems within 10; understand taking away',
    biblicalConnection: 'Sometimes we lose things, but God remains constant (Psalm 23:4)',
    materials: ['Ten-frame', 'Counters', 'Picture cards', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `We're SUBTRACTING—taking away! I have 7 counters (show 7 on ten-frame). I take away 2 (remove 2). How many are left? Count: 1, 2, 3, 4, 5. We have 5! 7 - 2 = 5. Again: Start with 8 (show 8). Take away 3 (remove 3). Count: 1, 2, 3, 4, 5. We have 5! 8 - 3 = 5. Subtraction means taking away to find what's left!`,
      steps: [
        'Show starting amount on ten-frame',
        'Remove the amount to take away',
        'Count remaining',
        'Write number sentence',
        'Repeat with new amounts',
      ],
    },
    guidedPractice: {
      description: 'Adult shows start amount. Child removes and tells what\'s left.',
      example: 'Adult: "Start with 6. Take away 2." Child shows 4 left.',
    },
    independentActivity: {
      description: 'Solve subtraction problems within 10',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Subtraction Facts Within 10',
      fileUrl: '/worksheets/week-07/1st/Math_Subtraction_10.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Subtraction Stories',
      fileUrl: '/worksheets/week-07/1st/Challenge_Subtraction_Stories.pdf',
      description: 'Write and solve subtraction word problems',
    },
    answerKey: '7-2=5, 8-3=5, 9-4=5, 10-2=8. All subtraction facts correct.',
    ifStruggling: 'Use only subtraction within 5. Use concrete counters.',
    ifAdvanced: 'Write subtraction sentences independently; solve two-step problems',
  },
]

// ==================== WEEK 8: Fall Harvest ====================

const week8Lessons: Lesson[] = [
  {
    id: 'l-w8-mon-pre-k-lit',
    title: 'Harvest & Seasons (Letter P)',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 8,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 8,
    essential: true,
    owner: 'shared',
    learningObjective: 'Understand harvest; recognize letter P; name seasonal changes',
    biblicalConnection: 'God provides harvest and food (Psalm 65:11, 1 Thessalonians 5:18)',
    materials: ['Fall pictures (leaves, harvest)', 'Letter P card', 'Crayons'],
    momTime: {
      duration: 8,
      script: `Fall is here! Look at the leaves—they're changing colors. Red, orange, yellow. Farmers HARVEST food. They pick apples, pumpkins, corn. Harvest means picking food from the garden. We say THANK YOU to God for our food! We're learning letter P. P is for PUMPKIN, PICK, and PLANT! Let's trace P!`,
      steps: [
        'Show fall pictures (leaves, harvest)',
        'Name harvest crops: pumpkin, apple, corn',
        'Introduce letter P with /p/ sound',
        'Say P words: pumpkin, pick, plant',
        'Trace P in air',
      ],
    },
    guidedPractice: {
      description: 'Teacher shows harvest picture. Child identifies the food.',
      example: 'Teacher shows pumpkin. Child: "Pumpkin! For harvest!"',
    },
    independentActivity: {
      description: 'Draw harvest foods; trace letter P',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Harvest & Seasons (Letter P)',
      fileUrl: '/worksheets/week-08/pre-k/Monday_Literacy_Harvest.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Harvest Collection',
      fileUrl: '/worksheets/week-08/pre-k/Challenge_Harvest.pdf',
      description: 'Draw all the foods from fall harvest',
    },
    answerKey: 'Harvest foods identified. Letter P traced. Drawings show seasonal change.',
    ifStruggling: 'Focus on 2 harvest foods (apple, pumpkin). Skip letter P.',
    ifAdvanced: 'Describe where each food grows and how to prepare it',
  },

  {
    id: 'l-w8-mon-pre-k-math',
    title: 'Counting by Tens: Groups of 10',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 8,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Recognize 10; count to 20; understand groups of 10',
    biblicalConnection: 'God's Ten Commandments show us how to live well (Exodus 20:1-17)',
    materials: ['Counters grouped in tens', 'Ten-frame', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `We're learning about TENS! Count with me: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10. TEN! Look—10 counters. Now I add 10 more. Count: 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20. TWENTY! We have two tens = twenty. Let's count: ten, twenty. Groups of 10 help us count fast!`,
      steps: [
        'Show 10 counters: count 1-10',
        'Show another 10: count 10-20',
        'Say: "10 and 10 makes 20"',
        'Create more groups of 10',
        'Count by tens',
      ],
    },
    guidedPractice: {
      description: 'Adult shows groups of 10. Child counts by tens.',
      example: 'Show 3 groups of 10. Child: "10, 20, 30."',
    },
    independentActivity: {
      description: 'Count and make groups of 10',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Groups of Ten & Counting to 20',
      fileUrl: '/worksheets/week-08/pre-k/Math_Tens.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Count by Tens to 30',
      fileUrl: '/worksheets/week-08/pre-k/Challenge_Tens.pdf',
      description: 'Count by tens to 30; identify tens and ones',
    },
    answerKey: 'Counting accurate: 1-20, 10-20, by tens. Groups of 10 identified.',
    ifStruggling: 'Count only to 10. Focus on one group of 10.',
    ifAdvanced: 'Count by tens to 50; show 30, 40, 50 with objects',
  },

  {
    id: 'l-w8-mon-k-lit',
    title: 'Beginning Sound /P/: Pumpkin, Pick, Pig',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 8,
    day: 'monday',
    gradeBand: 'k',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Identify /p/ sound; read beginning P words',
    biblicalConnection: 'God provides all we need (Matthew 6:11)',
    materials: ['Picture cards (pumpkin, pick, pig, pig, pot)', 'Letter P card', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `Today we learn /P/. Listen—it's a pop sound: /P/! Now say: /P/. Here are words: PUMPKIN, PICK, PIG, PAN, POT. Hear the /P/? /P/-umpkin, /P/-ick, /P/-ig. Let's read: "Pick the pumpkin." Good!`,
      steps: [
        'Model /p/ sound (pop/puff)',
        'Show picture cards: pumpkin, pick, pig, pan, pot',
        'Say each word emphasizing /p/',
        'Child repeats',
        'Read simple P sentences',
      ],
    },
    guidedPractice: {
      description: 'Adult shows picture. Child says /P/ word.',
      example: 'Adult shows pumpkin. Child: "Pumpkin! /P/-umpkin."',
    },
    independentActivity: {
      description: 'Circle P words; read sentences',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Beginning Sound /P/: Pictures & Words',
      fileUrl: '/worksheets/week-08/k/Monday_Literacy_P_Sound.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! /P/ Sentences',
      fileUrl: '/worksheets/week-08/k/Challenge_P_Sentences.pdf',
      description: 'Read and illustrate sentences with /P/ words',
    },
    answerKey: 'Circled P words: pumpkin, pick, pig, pan, pot. Sentences correct.',
    ifStruggling: 'Practice /p/ sound. Use only pumpkin and pig.',
    ifAdvanced: 'Find P words in books and classroom',
  },

  {
    id: 'l-w8-mon-k-math',
    title: 'Adding & Subtracting Within 5: Review',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 8,
    day: 'monday',
    gradeBand: 'k',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Solve addition and subtraction facts within 5 (review)',
    biblicalConnection: 'Practice and repetition help us grow strong (Hebrews 10:24-25)',
    materials: ['Counters', 'Ten-frame', 'Picture cards', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `We've learned so much! Let's review adding and subtracting. I have 2 apples (show 2). I add 3 more (add 3). Count: 1, 2, 3, 4, 5. So 2 + 3 = 5. Now: I have 5 apples. I eat 1. How many left? Count: 1, 2, 3, 4. So 5 - 1 = 4. Let's try more!`,
      steps: [
        'Show addition within 5 (3+2, 4+1, 2+3)',
        'Show subtraction within 5 (5-1, 4-2, 3-1)',
        'Count and verify each',
        'Write number sentences',
        'Mix add and subtract',
      ],
    },
    guidedPractice: {
      description: 'Adult gives problem. Child solves with counters.',
      example: 'Adult: "3 plus 1?" Child shows 4 counters.',
    },
    independentActivity: {
      description: 'Solve mixed addition and subtraction within 5',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Review: Adding & Subtracting Within 5',
      fileUrl: '/worksheets/week-08/k/Math_Review_5.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Mixed Problems',
      fileUrl: '/worksheets/week-08/k/Challenge_Mixed_5.pdf',
      description: 'Solve mixed addition and subtraction within 10',
    },
    answerKey: 'Addition facts correct (3+2=5, 4+1=5). Subtraction facts correct (5-1=4, 4-2=2).',
    ifStruggling: 'Use only 2-3 facts. Use concrete counters throughout.',
    ifAdvanced: 'Extend to within 10; write number sentences independently',
  },

  {
    id: 'l-w8-mon-1st-lit',
    title: 'Blending P Words & Sight Words Review',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 8,
    day: 'monday',
    gradeBand: '1st',
    minutes: 10,
    essential: true,
    owner: 'shared',
    learningObjective: 'Blend P words; review sight words from previous weeks',
    biblicalConnection: 'God celebrates our growth and progress (Philippians 3:14)',
    materials: ['Word cards (pan, pat, pet, pig)', 'Sight word cards (I, see, care, can)', 'Worksheet'],
    momTime: {
      duration: 10,
      script: `Let's blend /P/ words: /p/-/a/-/n/ = PAN. /p/-/a/-/t/ = PAT. /p/-/e/-/t/ = PET. /p/-/i/-/g/ = PIG. Now let's review sight words we learned: I, see, care, can. Read these: "I see the pig." "I can pet the pig." Great reading!`,
      steps: [
        'Sound out: /p/-/a/-/n/... PAN',
        'Continue: pat, pet, pig',
        'Review sight words: I, see, care, can',
        'Read sentences with blended + sight words',
        'Celebrate progress!',
      ],
    },
    guidedPractice: {
      description: 'Adult shows word. Child blends or reads.',
      example: 'Adult: "p-a-n?" Child: "/p/-/a/-/n/... PAN!"',
    },
    independentActivity: {
      description: 'Blend P words and read mixed sentences',
      isHandsOn: false,
    },
    requiredWorksheet: {
      title: 'Blending: P Words & Review',
      fileUrl: '/worksheets/week-08/1st/Monday_Literacy_P_Review.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Reading Fluency',
      fileUrl: '/worksheets/week-08/1st/Challenge_P_Sentences.pdf',
      description: 'Read sentences with P words and all sight words learned',
    },
    answerKey: 'P words blended: pan, pat, pet, pig. Sight words accurate. Sentences read fluently.',
    ifStruggling: 'Focus on pan and pig. Review only I, see.',
    ifAdvanced: 'Write own sentences using P words and sight words',
  },

  {
    id: 'l-w8-mon-1st-math',
    title: 'Addition & Subtraction Review: Facts to 10',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 8,
    day: 'monday',
    gradeBand: '1st',
    minutes: 12,
    essential: true,
    owner: 'shared',
    learningObjective: 'Solve addition and subtraction facts to 10; understand relationships',
    biblicalConnection: 'God's wisdom teaches us to choose wisely (Proverbs 2:6-7)',
    materials: ['Ten-frame', 'Counters', 'Number cards', 'Worksheet'],
    momTime: {
      duration: 12,
      script: `We're getting fast at addition and subtraction! Let's review. Addition: 5 + 3 = 8. 6 + 2 = 8. See? Different ways to make 8! Subtraction: 10 - 2 = 8. 9 - 1 = 8. Also make 8! We're learning that numbers are connected. Let's try: 7 + 2. Show me with your counters... 9! Good!`,
      steps: [
        'Show related facts (5+3=8, 6+2=8)',
        'Show inverse facts (10-2=8, 9-1=8)',
        'Use ten-frame for visualization',
        'Solve problems with missing addend',
        'Discuss number relationships',
      ],
    },
    guidedPractice: {
      description: 'Adult gives problem. Child solves and explains.',
      example: 'Adult: "6 plus 3?" Child shows 9, tells how they know.',
    },
    independentActivity: {
      description: 'Solve addition and subtraction facts to 10',
      isHandsOn: true,
    },
    requiredWorksheet: {
      title: 'Addition & Subtraction Review: Facts to 10',
      fileUrl: '/worksheets/week-08/1st/Math_Review_10.pdf',
    },
    challengeWorksheet: {
      title: '⭐ Challenge Me! Number Relationships',
      fileUrl: '/worksheets/week-08/1st/Challenge_Relationships.pdf',
      description: 'Find related addition and subtraction facts; explore patterns',
    },
    answerKey: 'Addition facts to 10 correct. Subtraction facts to 10 correct. Relationships identified.',
    ifStruggling: 'Review only facts within 5. Use concrete manipulatives.',
    ifAdvanced: 'Explore fact families (3+4=7, 4+3=7, 7-3=4, 7-4=3)',
  },
]

export const curriculumLessons: Lesson[] = [
  ...week1Lessons,
  ...week2Lessons,
  ...week3Lessons,
  ...week4Lessons,
  ...week5Lessons,
  ...week6Lessons,
  ...week7Lessons,
  ...week8Lessons,
  // Weeks 9-36: Continue systematically...
]

/**
 * Helper: Get all lessons for a week
 */
export function getLessonsForWeek(weekNumber: number): Lesson[] {
  return curriculumLessons.filter((l) => l.weekNumber === weekNumber)
}

/**
 * Helper: Get lessons for a specific child (grade band)
 */
export function getLessonsForChild(
  weekNumber: number,
  day: string,
  gradeBand: string,
): Lesson[] {
  return curriculumLessons.filter(
    (l) => l.weekNumber === weekNumber && l.day === day && l.gradeBand === gradeBand,
  )
}
