import type {
  Assignment,
  Child,
  CoverageRequest,
  CurriculumWeek,
  Household,
  Lesson,
  ParentNote,
  ReadAloudBook,
  Resource,
  Skill,
  SupplyItem,
} from './types'

export const DEMO_DAY = 'tuesday' as const
export const DEMO_WEEK = 1

export const households: Household[] = [
  { id: 'h-venessa', name: "Venessa's Homeschool", momName: 'Venessa', momInitial: 'V' },
  { id: 'h-lola', name: "Damilola's Homeschool", momName: 'Damilola', momInitial: 'D' },
]

export const children: Child[] = [
  {
    id: 'c-alijah',
    name: 'Alijah',
    grade: '1st Grade',
    gradeBand: '1st',
    householdId: 'h-venessa',
    color: 'child-alijah',
    childMode: true,
    lowDistraction: false,
  },
  {
    id: 'c-olori',
    name: 'Olori-Joy',
    grade: 'Kindergarten',
    gradeBand: 'k',
    householdId: 'h-venessa',
    color: 'child-olori',
    childMode: false,
    lowDistraction: false,
  },
  {
    id: 'c-seraiah',
    name: 'Seraiah',
    grade: 'Pre-K',
    gradeBand: 'pre-k',
    householdId: 'h-venessa',
    color: 'child-seraiah',
    childMode: false,
    lowDistraction: false,
  },
  {
    id: 'c-amelia',
    name: 'Amelia',
    grade: 'Pre-K',
    gradeBand: 'pre-k',
    householdId: 'h-lola',
    color: 'child-amelia',
    childMode: false,
    lowDistraction: false,
  },
]

export const weeks: CurriculumWeek[] = [
  {
    id: 'w1',
    number: 1,
    theme: 'God Created Me & My World',
    bibleRef: 'Genesis 1',
    bigIdea: 'God made everything — and He made me on purpose.',
    memoryVerse: 'God saw all that he had made, and it was very good.',
    memoryVerseRef: 'Genesis 1:31',
    art: ['Creation Day collage', '"God Made Me Special" self portrait'],
    science: ['Living vs Nonliving', 'Five Senses'],
  },
  {
    id: 'w2',
    number: 2,
    theme: 'Noah: Weather, Water & God\u2019s Promise',
    bibleRef: 'Genesis 6\u20139',
    bigIdea: 'God keeps His promises, and the rainbow reminds us.',
    memoryVerse: 'I have set my rainbow in the clouds.',
    memoryVerseRef: 'Genesis 9:13',
    art: ['Rainbow resist', 'Ark craft'],
    science: ['Weather observation', 'Sink or float'],
  },
  {
    id: 'w3',
    number: 3,
    theme: 'Joseph: Colors, Patterns & Feelings',
    bibleRef: 'Genesis 37, 39\u201345',
    bigIdea: 'God can turn hard things into good things.',
    memoryVerse: 'You intended to harm me, but God intended it for good.',
    memoryVerseRef: 'Genesis 50:20',
    art: ['Colorful coat collage', 'Pattern weaving'],
    science: ['Color mixing', 'Texture investigation'],
  },
  {
    id: 'w4',
    number: 4,
    theme: 'Moses: Light, Sound & Courage',
    bibleRef: 'Exodus 2\u201314',
    bigIdea: 'God gives us courage to do hard things.',
    memoryVerse: 'The Lord will fight for you; you need only to be still.',
    memoryVerseRef: 'Exodus 14:14',
    art: ['Burning bush craft', 'Shadow art'],
    science: ['Light and shadows', 'Sound and vibration'],
  },
  {
    id: 'w5',
    number: 5,
    theme: 'David & Goliath: Strength, Measurement & Growth',
    bibleRef: '1 Samuel 17',
    bigIdea: 'God makes us brave when we trust Him.',
    memoryVerse: 'The battle is the Lord\u2019s.',
    memoryVerseRef: '1 Samuel 17:47',
    art: ['Five-stone craft', 'Goliath measurement art'],
    science: ['Measurement', 'Plant growth'],
  },
]

// ---- Lessons (seeded for Week 1) --------------------------------------------

export const lessons: Lesson[] = [
  // Shared family Bible — assigned to everyone
  {
    id: 'l-bible-w1',
    title: 'Family Bible: God Created Everything',
    subject: 'bible',
    activityType: 'mom-time',
    weekNumber: 1,
    day: 'tuesday',
    gradeBand: 'pre-k',
    minutes: 7,
    essential: true,
    owner: 'shared',
    youNeed: ['A Bible', 'Optional: crayons for coloring page'],
    teach: [
      'Read Genesis 1:1\u20135 together.',
      'Point to things in the room and ask "Did God make this, or did people make this?"',
      'Practice the memory verse: Genesis 1:31.',
    ],
    ask: ['What did God create?', 'What is your favorite thing God made?'],
    watchFor: 'Little ones losing focus — keep it to 7 minutes and stay warm.',
    interactive: 'memory-verse',
    printable: true,
  },
  // Alijah (1st)
  {
    id: 'l-alijah-math-w1',
    title: 'Number Bonds to 10',
    subject: 'math',
    activityType: 'mom-time',
    weekNumber: 1,
    day: 'tuesday',
    gradeBand: '1st',
    minutes: 8,
    essential: true,
    owner: 'h-venessa',
    youNeed: ['7 counters (or LEGO, beans, buttons)'],
    teach: [
      'Put 7 counters on the table.',
      'Move 3 to one side and 4 to the other.',
      'Say: "7 is made of 3 and 4."',
    ],
    ask: ['What two parts make 7?', 'Can you show me another way to make 7?'],
    watchFor: 'Recounting everything instead of recognizing the parts.',
    interactive: 'math-manipulatives',
    printable: true,
  },
  {
    id: 'l-alijah-lit-w1',
    title: 'Short A: Decodable Reading',
    subject: 'literacy',
    activityType: 'independent',
    weekNumber: 1,
    day: 'tuesday',
    gradeBand: '1st',
    minutes: 10,
    essential: true,
    owner: 'h-venessa',
    interactive: 'phonics',
    printable: true,
  },
  {
    id: 'l-alijah-sci-w1',
    title: 'Living vs Nonliving Sort',
    subject: 'science',
    activityType: 'hands-on',
    weekNumber: 1,
    day: 'tuesday',
    gradeBand: '1st',
    minutes: 12,
    essential: false,
    owner: 'shared',
    printable: true,
  },
  // Olori-Joy (K)
  {
    id: 'l-olori-lit-w1',
    title: 'Letter Sound /\u0103/ — Multisensory',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 1,
    day: 'tuesday',
    gradeBand: 'k',
    minutes: 6,
    essential: true,
    owner: 'h-venessa',
    youNeed: ['Sand or salt tray (optional)'],
    teach: [
      'Say "/\u0103/ like apple." Have her repeat it 3 times.',
      'Show the letter A and 3 picture cards.',
      'Trace A together in the air.',
    ],
    ask: ['What sound does A make?', 'Can you find something that starts with /\u0103/?'],
    watchFor: 'Confusing letter name "ay" with the sound "/\u0103/".',
    interactive: 'phonics',
    printable: true,
  },
  {
    id: 'l-olori-math-w1',
    title: 'Counting 0\u201310 and +1',
    subject: 'math',
    activityType: 'independent',
    weekNumber: 1,
    day: 'tuesday',
    gradeBand: 'k',
    minutes: 8,
    essential: true,
    owner: 'h-venessa',
    interactive: 'math-manipulatives',
    printable: true,
  },
  {
    id: 'l-olori-sci-w1',
    title: 'Five Senses Walk',
    subject: 'science',
    activityType: 'optional',
    weekNumber: 1,
    day: 'tuesday',
    gradeBand: 'k',
    minutes: 10,
    essential: false,
    owner: 'shared',
  },
  // Seraiah (Pre-K, Venessa)
  {
    id: 'l-seraiah-math-w1',
    title: 'Count Objects 1\u20135',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 1,
    day: 'tuesday',
    gradeBand: 'pre-k',
    minutes: 6,
    essential: true,
    owner: 'shared',
    interactive: 'math-manipulatives',
    printable: true,
  },
  {
    id: 'l-seraiah-lit-w1',
    title: 'Letter A Exposure & Trace',
    subject: 'literacy',
    activityType: 'hands-on',
    weekNumber: 1,
    day: 'tuesday',
    gradeBand: 'pre-k',
    minutes: 5,
    essential: true,
    owner: 'shared',
    interactive: 'phonics',
    printable: true,
  },
  // Amelia (Pre-K, Damilola) — shares the same Pre-K lessons
  {
    id: 'l-amelia-math-w1',
    title: 'Count Objects 1\u20135',
    subject: 'math',
    activityType: 'hands-on',
    weekNumber: 1,
    day: 'tuesday',
    gradeBand: 'pre-k',
    minutes: 6,
    essential: true,
    owner: 'shared',
    interactive: 'math-manipulatives',
    printable: true,
  },
  {
    id: 'l-amelia-lit-w1',
    title: 'Letter A Exposure & Trace',
    subject: 'literacy',
    activityType: 'hands-on',
    weekNumber: 1,
    day: 'tuesday',
    gradeBand: 'pre-k',
    minutes: 5,
    essential: true,
    owner: 'shared',
    interactive: 'phonics',
    printable: true,
  },
  // A shared Pre-K letter lesson used by Seraiah + Amelia (Monday)
  {
    id: 'l-shared-letterA',
    title: 'Letter A Multisensory Practice',
    subject: 'literacy',
    activityType: 'mom-time',
    weekNumber: 1,
    day: 'monday',
    gradeBand: 'pre-k',
    minutes: 6,
    essential: true,
    owner: 'shared',
    interactive: 'phonics',
    printable: true,
  },
]

export const assignments: Assignment[] = [
  // Bible — everyone. Some already done.
  { id: 'a1', lessonId: 'l-bible-w1', childId: 'c-alijah', status: 'done', completedAt: '' },
  { id: 'a2', lessonId: 'l-bible-w1', childId: 'c-olori', status: 'done', completedAt: '' },
  { id: 'a3', lessonId: 'l-bible-w1', childId: 'c-seraiah', status: 'done', completedAt: '' },
  { id: 'a4', lessonId: 'l-bible-w1', childId: 'c-amelia', status: 'done', completedAt: '' },
  // Alijah — 2 of 4 done
  { id: 'a5', lessonId: 'l-alijah-math-w1', childId: 'c-alijah', status: 'done', completedAt: '' },
  { id: 'a6', lessonId: 'l-alijah-lit-w1', childId: 'c-alijah', status: 'todo' },
  { id: 'a7', lessonId: 'l-alijah-sci-w1', childId: 'c-alijah', status: 'todo' },
  // Olori-Joy — 1 of 4 done (bible only)
  { id: 'a8', lessonId: 'l-olori-lit-w1', childId: 'c-olori', status: 'todo' },
  { id: 'a9', lessonId: 'l-olori-math-w1', childId: 'c-olori', status: 'todo' },
  { id: 'a10', lessonId: 'l-olori-sci-w1', childId: 'c-olori', status: 'todo' },
  // Seraiah — 3 of 3 (small load) — mark 2 more done
  { id: 'a11', lessonId: 'l-seraiah-math-w1', childId: 'c-seraiah', status: 'done', completedAt: '' },
  { id: 'a12', lessonId: 'l-seraiah-lit-w1', childId: 'c-seraiah', status: 'done', completedAt: '' },
  // Amelia — Damilola's household
  { id: 'a13', lessonId: 'l-amelia-math-w1', childId: 'c-amelia', status: 'done', completedAt: '' },
  { id: 'a14', lessonId: 'l-amelia-lit-w1', childId: 'c-amelia', status: 'todo' },
]

export const skills: Skill[] = [
  // Alijah literacy
  { id: 's1', childId: 'c-alijah', track: 'literacy', name: 'CVC Blending', status: 'mastered' },
  { id: 's2', childId: 'c-alijah', track: 'literacy', name: 'Short A', status: 'mastered' },
  { id: 's3', childId: 'c-alijah', track: 'literacy', name: 'Short E', status: 'practicing' },
  { id: 's4', childId: 'c-alijah', track: 'literacy', name: 'Digraph SH', status: 'learning' },
  { id: 's5', childId: 'c-alijah', track: 'literacy', name: 'Fluency', status: 'practicing' },
  // Alijah math
  { id: 's6', childId: 'c-alijah', track: 'math', name: 'Number Bonds', status: 'practicing' },
  { id: 's7', childId: 'c-alijah', track: 'math', name: 'Addition within 10', status: 'practicing' },
  { id: 's8', childId: 'c-alijah', track: 'math', name: 'Word Problems', status: 'learning' },
  // Olori-Joy literacy
  { id: 's9', childId: 'c-olori', track: 'literacy', name: 'Phonemic Awareness', status: 'practicing' },
  { id: 's10', childId: 'c-olori', track: 'literacy', name: 'Letter Sounds', status: 'learning' },
  { id: 's11', childId: 'c-olori', track: 'literacy', name: 'Oral Blending', status: 'learning' },
  { id: 's12', childId: 'c-olori', track: 'math', name: 'Counting to 10', status: 'practicing' },
  { id: 's13', childId: 'c-olori', track: 'math', name: 'Number Sense', status: 'learning' },
  // Seraiah
  { id: 's14', childId: 'c-seraiah', track: 'literacy', name: 'Letter Exposure', status: 'learning' },
  { id: 's15', childId: 'c-seraiah', track: 'literacy', name: 'Phonological Awareness', status: 'learning' },
  { id: 's16', childId: 'c-seraiah', track: 'math', name: 'Counting 1\u20135', status: 'practicing' },
  { id: 's17', childId: 'c-seraiah', track: 'math', name: 'Shapes', status: 'learning' },
  // Amelia
  { id: 's18', childId: 'c-amelia', track: 'literacy', name: 'Letter Exposure', status: 'practicing' },
  { id: 's19', childId: 'c-amelia', track: 'literacy', name: 'Phonological Awareness', status: 'learning' },
  { id: 's20', childId: 'c-amelia', track: 'math', name: 'Counting 1\u20135', status: 'learning' },
  { id: 's21', childId: 'c-amelia', track: 'math', name: 'Sorting', status: 'learning' },
]

export const resources: Resource[] = [
  { id: 'r1', title: 'Short A Word Family Cards', type: 'Flash Cards', subject: 'literacy', skill: 'Short A', gradeBand: '1st', weekNumber: 1, minutes: 10, owner: 'shared', contributor: 'Venessa' },
  { id: 'r2', title: 'Number Bonds to 10 Practice', type: 'Math Practice', subject: 'math', skill: 'Number Bonds', gradeBand: '1st', weekNumber: 1, minutes: 15, owner: 'h-venessa', contributor: 'Venessa' },
  { id: 'r3', title: 'Letter A Tracing Page', type: 'Tracing', subject: 'literacy', skill: 'Handwriting', gradeBand: 'pre-k', weekNumber: 1, minutes: 8, owner: 'shared', contributor: 'Damilola' },
  { id: 'r4', title: 'Creation Days Coloring Book', type: 'Coloring', subject: 'bible', skill: 'Creation', gradeBand: 'pre-k', weekNumber: 1, minutes: 12, owner: 'shared', contributor: 'Venessa' },
  { id: 'r5', title: 'Living vs Nonliving Cut & Paste', type: 'Cut & Paste', subject: 'science', skill: 'Classification', gradeBand: 'k', weekNumber: 1, minutes: 10, owner: 'shared', contributor: 'Damilola' },
  { id: 'r6', title: 'Count & Color 1\u20135', type: 'Worksheet', subject: 'math', skill: 'Counting', gradeBand: 'pre-k', weekNumber: 1, minutes: 8, owner: 'shared', contributor: 'Damilola' },
  { id: 'r7', title: 'Genesis 1 Read-Aloud Mini Book', type: 'Mini Book', subject: 'bible', skill: 'Creation', gradeBand: 'k', weekNumber: 1, minutes: 10, owner: 'shared', contributor: 'Venessa' },
  { id: 'r8', title: 'Short A Decodable Passage', type: 'Reading Passage', subject: 'literacy', skill: 'Decodable Reading', gradeBand: '1st', weekNumber: 1, minutes: 12, owner: 'h-venessa', contributor: 'Venessa' },
]

export const readAloud: ReadAloudBook[] = [
  { id: 'b1', title: 'The Berenstain Bears and the Spooky Old Tree', status: 'currently-reading', householdId: 'h-venessa' },
  { id: 'b2', title: 'Blueberries for Sal', status: 'favorite', householdId: 'h-venessa' },
  { id: 'b3', title: 'The Big Book of Weather', status: 'library', householdId: 'h-venessa' },
  { id: 'b4', title: 'God Made the World', status: 'finished', householdId: 'h-lola' },
]

export const supplies: SupplyItem[] = [
  { id: 'sp1', label: "Print Monday & Tuesday packets", section: 'print', have: false },
  { id: 'sp2', label: '7 counters (or LEGO / beans)', section: 'household', have: true, substitute: 'LEGO, beans, buttons, or snacks' },
  { id: 'sp3', label: 'Construction paper', section: 'craft', have: true },
  { id: 'sp4', label: 'Glue & crayons', section: 'craft', have: true },
  { id: 'sp5', label: 'Small objects for living/nonliving sort', section: 'science', have: false },
  { id: 'sp6', label: 'Sand or salt tray', section: 'optional', have: false, substitute: 'Shaving cream or a textured tracing card' },
]

export const coverageRequests: CoverageRequest[] = []

export const parentNotes: ParentNote[] = []
